#!/bin/sh
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/02 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/03 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/04 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/05 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/06 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/07 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/08 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/09 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/10 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/11 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/12 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/13 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/14 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/15 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/16 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/17 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/18 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/19 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/20 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/21 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/22 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/23 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/24 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/25 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/26 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/27 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/28 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/29 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/30 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/31 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/33 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/34 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/35 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/36 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/37 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/38 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/39 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/40 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/41 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/42 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/43 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/44 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/45 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/46 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/48 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/49 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/50 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/51 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/52 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/53 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/54 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/57 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/58 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/59 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/60 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/61 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/62 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/63 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/64 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/66 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/67 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/69 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/70 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/71 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/72 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/73 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/75 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/76 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/77 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/78 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/79 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/80 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/81 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/82 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/83 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/84 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/85 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/86 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/87 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/89 -type f|wc
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/90 -type f|wc
