#!/bin/sh
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/76 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/77 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/78 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/79 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/80 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/81 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/82 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/83 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/84 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/85 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/86 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/87 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/89 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
find /mnt/public-nfs/posda/import/ACRIN-FLT-Breast-DeIdFiles/90 -type f|FileImportIntoPosdaMetered.pl "directory scan" "Import of ACRIN-FLT after CTP applied"
