#!/bin/bash
export POSDA_IMG_VERSION=1.0.3

echo "Setting up your environment..."

if [ ! -f docker-compose.yaml ]; then
  cp config/docker-compose.yaml .
fi

if [ ! -f api.env ]; then
  cp config/api.env .
fi

if [ ! -f database.env ]; then
  cp config/database.env .
fi

if [ ! -f nbia.env ]; then
  cp config/nbia.env .
fi

if [ ! -f common.env ]; then
  cp config/common.env .
fi

if [ ! -f ream.env ]; then
  cp config/ream.env .
fi

if [ ! -f exodus.env ]; then
  cp config/exodus.env .
fi

if [ ! -f posda.env ]; then
  cp config/posda.env .
fi

docker image pull tcia/exodus:${POSDA_IMG_VERSION}
docker image pull tcia/ream:${POSDA_IMG_VERSION}
docker image pull tcia/lanterna:${POSDA_IMG_VERSION}
docker image pull tcia/posda:${POSDA_IMG_VERSION}
docker image pull tcia/posda_web:${POSDA_IMG_VERSION}
docker image pull tcia/kaleidoscope:${POSDA_IMG_VERSION}
