#!/bin/bash

echo "Setting up your environment..."

if [ ! -f docker-compose.yaml ]; then
  cp config/docker-compose.yaml .
fi

if [ ! -f api.env ]; then
  cp config/api.env .
fi

if [ ! -f database.env ]; then
  cp config/database.env .
fi

if [ ! -f nbia.env ]; then
  cp config/nbia.env .
fi

if [ ! -f common.env ]; then
  cp config/common.env .
fi

if [ ! -f ream.env ]; then
  cp config/ream.env .
fi

if [ ! -f exodus.env ]; then
  cp config/exodus.env .
fi

if [ ! -f posda.env ]; then
  cp config/posda.env .
fi

docker pull tcia/posda:latest
docker pull tcia/kaleidoscope:latest
docker pull tcia/k-base:latest
docker pull tcia/ream:latest
docker pull tcia/exodus:latest
docker pull tcia/lanterna:latest
docker pull tcia/posda_web:latest
