#!/usr/bin/env bash
set -e

help() {
    echo "Posda Docker Edition (DE) Management Script

This script is intended for use mainly in development environments,
and as such all commands operate using the dev docker-compose file.

Supported operations:
    help - this help
    up - bring up all containers via docker-compose
         specify -d to detatch (attached by default)
    down - bring down all containers via docker-compose
    restart - restart containers without removing
    psql - execute the PostgreSQL shell inside the running db container
    shell - open a Posda Shell inside the main Posda container
    logs - open and follow the full logs
    "
}


case "$1" in
  restart)
    shift
    exec docker-compose restart $*
    ;;
  up)
    shift
    make -C posda posdatools/posda.env
    exec docker-compose up $*
    ;;

  down)
    shift
    exec docker-compose down $*
    ;;

  psql)
    shift
    exec docker-compose exec db psql -U postgres $*
    ;;

  shell)
    shift
    exec docker-compose exec posda bash -c 'cd /home/posda/posdatools; ./posda_shell'
    ;;

  logs)
    shift
    exec docker-compose logs -f --tail=10
    ;;

  help)
    shift
    help
    ;;

  *)
    help
    ;;
esac
