#!/bin/bash
set -e

help() {
    echo "Posda Docker Edition (DE) Management Script

This script is intended for use mainly in development environments,
and as such all commands operate using the dev docker-compose file.

Supported operations:
    help - this help
    up - bring up all containers via docker-compose
         specify -d to detatch (attached by default)
    down - bring down all containers via docker-compose
    restart - restart containers without removing
    psql - execute the PostgreSQL shell inside the running db container
    shell - open a Posda Shell inside the main Posda container
    logs - open and follow the full logs
    "
}

# Figure out which docker compose to use, if any are installed
DOCKER="docker compose"

if ! docker compose version 2>/dev/null >/dev/null; then
	DOCKER="docker-compose --compatibility"
	if ! [[ $(type -P "docker-compose") ]] ; then
		echo "Did not detect 'docker-compose' or 'docker compose'."\
			 "At least one is required!"
		exit 1;
	fi
fi


case "$1" in
  restart)
    shift
    git describe --tags > posda/posdatools/versionInfo.txt
    exec $DOCKER restart $*
    ;;
  up)
    shift
    git describe --tags > posda/posdatools/versionInfo.txt
    exec $DOCKER up $*
    ;;

  down)
    shift
    exec $DOCKER down $*
    ;;

  psql)
    shift
    exec $DOCKER exec db psql -U postgres $*
    ;;

  shell)
    shift
    exec $DOCKER exec posda bash -c 'cd /home/posda/posdatools; ./posda_shell'
    ;;

  logs)
    shift
    exec $DOCKER logs -f --tail=10 $*
    ;;

  help)
    shift
    help
    ;;

  *)
    exec $DOCKER $@
    ;;
esac
