#
(0029,0010) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0010) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS"		Keyword="Commentline"			Name="Commentline"
(0029,0020) VERS="CMT"	VR="DS"   VM="1"	Owner="CAMTRONICS"		Keyword="EdgeEnhancementCoefficient"	Name="Edge Enhancement Coefficient"
(0029,0020) VERS="CMT"	VR="UN"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0030) VERS="CMT"	VR="UN"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0040) VERS="CMT"	VR="UN"   VM="1"	Owner="CAMTRONICS IP"		Keyword="?"				Name="?"
(0029,0050) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS"		Keyword="SceneText"			Name="Scene Text"
(0029,0060) VERS="CMT"	VR="LT"   VM="1"	Owner="CAMTRONICS"		Keyword="ImageText"			Name="Image Text"
(0029,0070) VERS="CMT"	VR="IS"   VM="1"	Owner="CAMTRONICS"		Keyword="PixelShiftHorizontal"		Name="Pixel Shift Horizontal"
(0029,0080) VERS="CMT"	VR="IS"   VM="1"	Owner="CAMTRONICS"		Keyword="PixelShiftVertical"		Name="Pixel Shift Vertical"
(0029,0090) VERS="CMT"	VR="IS"   VM="1"	Owner="CAMTRONICS"		Keyword="?"				Name="?"
