#
(0029,0070) VERS="ISG"	VR="IS"   VM="1"	Owner="ISG shadow"	Keyword="?"						Name="?"
(0029,0080) VERS="ISG"	VR="IS"   VM="1"	Owner="ISG shadow"	Keyword="?"						Name="?"
(0029,0090) VERS="ISG"	VR="IS"   VM="1"	Owner="ISG shadow"	Keyword="?"						Name="?"

(0029,0013) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0014) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0017) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0018) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0019) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,001a) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,001b) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,001c) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,001d) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,001e) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0021) VERS="ISG"	VR="US"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0022) VERS="ISG"	VR="US"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0023) VERS="ISG"	VR="US"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0024) VERS="ISG"	VR="US"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0025) VERS="ISG"	VR="US"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0027) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0028) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0029) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0030) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0052) VERS="ISG"	VR="US"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0053) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0054) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0055) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0056) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"
(0029,0057) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette V1.0"	Keyword="?"						Name="?"

(0029,0000) VERS="ISG"	VR="UI"   VM="1"	Owner="Silhouette Graphics Export V1.0"	Keyword="?"				Name="?"

(0029,0011) VERS="ISG"	VR="IS"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineName"				Name="Line Name"
(0029,0012) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineNameFont"				Name="Line Name Font"
(0029,0013) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineNameDisplay"			Name="Line Name Display"
(0029,0014) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineNormalColor"			Name="Line Normal Color"
(0029,0015) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineType"				Name="Line Type"
(0029,0016) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineThickness"				Name="Line Thickness"
(0029,0017) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineStyle"				Name="Line Style"
(0029,0018) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineDashLength"			Name="Line Dash Length"
(0029,0019) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineInteractivity"			Name="Line Interactivity"
(0029,0020) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineMeasurementColor"			Name="Line Measurement Color"
(0029,0021) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineMeasurementFont"			Name="Line Measurement Font"
(0029,0022) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineMeasurementDashLength"		Name="Line Measurement Dash Length"
(0029,0023) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LinePointSpace"			Name="Line Point Space"
(0029,0024) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LinePoints"				Name="Line Points"
(0029,0025) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineControlPointSize"			Name="Line Control Point Size"
(0029,0026) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineControlPointSpace"			Name="Line Control Point Space"
(0029,0027) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineControlPoints"			Name="Line Control Points"
(0029,0028) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineLabel"				Name="Line Label"
(0029,0029) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Line V1.0"	Keyword="LineDontSave"				Name="Line Don't Save"

(0029,0041) VERS="ISG"	VR="SQ"   VM="1"	Owner="Silhouette Sequence Ids V1.0"	Keyword="?"				Name="?"
(0029,0042) VERS="ISG"	VR="SQ"   VM="1"	Owner="Silhouette Sequence Ids V1.0"	Keyword="?"				Name="?"
(0029,0043) VERS="ISG"	VR="SQ"   VM="1"	Owner="Silhouette Sequence Ids V1.0"	Keyword="?"				Name="?"

(0029,0011) VERS="ISG"	VR="IS"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationName"			Name="Annotation Name"
(0029,0012) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationFont"			Name="Annotation Font"
(0029,0013) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextForegroundColor"		Name="Annotation Text Foreground Color"
(0029,0014) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextBackgroundColor"		Name="Annotation Text Background Color"
(0029,0015) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextBackingMode"		Name="Annotation Text Backing Mode"
(0029,0016) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextJustification"		Name="Annotation Text Justification"
(0029,0017) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextLocation"		Name="Annotation Text Location"
(0029,0018) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextString"			Name="Annotation Text String"
(0029,0019) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextAttachMode"		Name="Annotation Text Attach Mode"
(0029,0020) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextCursorMode"		Name="Annotation Text Cursor Mode"
(0029,0021) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextShadowOffsetX"		Name="Annotation Text Shadow Offset X"
(0029,0022) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationTextShadowOffsetY"		Name="Annotation Text Shadow Offset Y"
(0029,0023) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLineColor"			Name="Annotation Line Color"
(0029,0024) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLineThickness"		Name="Annotation Line Thickness"
(0029,0025) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLineType"			Name="Annotation Line Type"
(0029,0026) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLineStyle"			Name="Annotation Line Style"
(0029,0027) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLineDashLength"		Name="Annotation Line Dash Length"
(0029,0028) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLineAttachMode"		Name="Annotation Line Attach Mode"
(0029,0029) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLinePointCount"		Name="Annotation Line Point Count"
(0029,0030) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLinePoints"			Name="Annotation Line Points"
(0029,0031) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationLineControlSize"		Name="Annotation Line Control Size"
(0029,0032) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationMarkerColor"			Name="Annotation Marker Color"
(0029,0033) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationMarkerType"			Name="Annotation Marker Type"
(0029,0034) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationMarkerSize"			Name="Annotation Marker Size"
(0029,0035) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationMarkerLocation"		Name="Annotation Marker Location"
(0029,0036) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationMarkerAttachMode"		Name="Annotation Marker Attach Mode"
(0029,0037) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationGeomColor"			Name="Annotation Geom Color"
(0029,0038) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationGeomThickness"		Name="Annotation Geom Thickness"
(0029,0039) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationGeomLineStyle"		Name="Annotation Geom Line Style"
(0029,0040) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationGeomDashLength"		Name="Annotation Geom Dash Length"
(0029,0041) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationGeomFillPattern"		Name="Annotation Geom Fill Pattern"
(0029,0042) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationInteractivity"		Name="Annotation Interactivity"
(0029,0043) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationArrowLength"			Name="Annotation Arrow Length"
(0029,0044) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationArrowAngle"			Name="Annotation Arrow Angle"
(0029,0045) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette Annot V1.0"	Keyword="AnnotationDontSave"			Name="Annotation Don't Save"

(0029,0011) VERS="ISG"	VR="IS"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIName"				Name="ROI Name"
(0029,0012) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROINameFont"				Name="ROI Name Font"
(0029,0013) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROINormalColor"			Name="ROI Normal Color"
(0029,0014) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIFillPattern"			Name="ROI Fill Pattern"
(0029,0015) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIBpSeg"				Name="ROI Bp Seg"
(0029,0016) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIBpSegPairs"				Name="ROI Bp Seg Pairs"
(0029,0017) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROISeedSpace"				Name="ROI Seed Space"
(0029,0018) VERS="ISG"	VR="UN"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROISeeds"				Name="ROI Seeds"
(0029,0019) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROILineThickness"			Name="ROI Line Thickness"
(0029,0020) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROILineStyle"				Name="ROI Line Style"
(0029,0021) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROILineDashLength"			Name="ROI Line Dash Length"
(0029,0022) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIInteractivity"			Name="ROI Interactivity"
(0029,0023) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROINamePosition"			Name="ROI Name Position"
(0029,0024) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROINameDisplay"			Name="ROI Name Display"
(0029,0025) VERS="ISG"	VR="LT"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROILabel"				Name="ROI Label"
(0029,0026) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShape"				Name="ROI Shape"
(0029,0027) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShapeTilt"				Name="ROI Shape Tilt"
(0029,0028) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShapePointsCount"			Name="ROI Shape Points Count"
(0029,0029) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShapePointsSpace"			Name="ROI Shape Points Space"
(0029,0030) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShapePoints"			Name="ROI Shape Points"
(0029,0031) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShapeControlPointsCount"		Name="ROI Shape Control Points Count"
(0029,0032) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShapeControlPointsSpace"		Name="ROI Shape Control Points Space"
(0029,0033) VERS="ISG"	VR="FD"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIShapeControlPoints"			Name="ROI Shape Control Points"
(0029,0034) VERS="ISG"	VR="UL"   VM="1"	Owner="Silhouette ROI V1.0"	Keyword="ROIDontSave"				Name="ROI Don't Save"
