#
(0003,0000) VERS="AEG"	VR="US"   VM="1-n"	Owner="AEGIS_DICOM_2.00"	Keyword="?"			Name="?"
(0005,0000) VERS="AEG"	VR="US"   VM="1-n"	Owner="AEGIS_DICOM_2.00"	Keyword="?"			Name="?"
(0009,0000) VERS="AEG"	VR="US"   VM="1-n"	Owner="AEGIS_DICOM_2.00"	Keyword="?"			Name="?"
(0009,0000) VERS="MRG"	VR="OB"   VM="1"	Owner="MERGE TECHNOLOGIES, INC."	Keyword="?"			Name="?"
(0011,0000) VERS="HOL"	VR="LO"   VM="1"	Owner="Hologic"	Keyword="HxQuestionnaire"			Name="Hx Questionnaire"
(0011,0000) VERS="HOL"	VR="LO"   VM="1"	Owner="HOLOGIC"	Keyword="HxQuestionnaire"			Name="Hx Questionnaire"
(0019,0000) VERS="AEG"	VR="US"   VM="1-n"	Owner="AEGIS_DICOM_2.00"	Keyword="?"			Name="?"
(0019,0010) VERS="DUP"	VR="ST"   VM="1"	Owner="1.2.840.113681"	Keyword="CRImageParamsCommon"			Name="CR Image Params Common"
(0019,0011) VERS="DUP"	VR="ST"   VM="1"	Owner="1.2.840.113681"	Keyword="CRImageIPParamsSingle"			Name="CR Image IP Params Single"
(0019,0012) VERS="DUP"	VR="ST"   VM="1"	Owner="1.2.840.113681"	Keyword="CRImageIPParamsLeft"			Name="CR Image IP Params Left"
(0019,0013) VERS="DUP"	VR="ST"   VM="1"	Owner="1.2.840.113681"	Keyword="CRImageIPParamsRight"			Name="CR Image IP Params Right"
(0019,0001) VERS="LDX"  VR="IS"   VM="1-n"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?" 
(0019,0002) VERS="LDX"  VR="IS"   VM="1"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?"
(0019,0003) VERS="LDX"  VR="DS"   VM="1"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?" 
(0019,0004) VERS="LDX"  VR="DS"   VM="1"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?" 
(0019,0005) VERS="LDX"  VR="DS"   VM="1"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?" 
(0019,0006) VERS="LDX"  VR="DS"   VM="1"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?" 
(0019,0007) VERS="LDX"  VR="DS"   VM="1"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?" 
(0019,0008) VERS="LDX"  VR="DS"   VM="1"	Owner="LODOX_STATSCAN"	Keyword="?"			Name="?" 
(0021,0001) VERS="SCH"	VR="UI"   VM="1"	Owner="SCHICK TECHNOLOGIES - Change List Creator ID"	Keyword="?"			Name="?"
(0021,0002) VERS="SCH"	VR="SQ"   VM="1"	Owner="SCHICK TECHNOLOGIES - Change List Creator ID"	Keyword="?"			Name="?"
(0021,0001) VERS="SCH"	VR="UI"   VM="1"	Owner="SCHICK TECHNOLOGIES - Note List Creator ID"	Keyword="?"			Name="?"
(0021,0002) VERS="SCH"	VR="SQ"   VM="1"	Owner="SCHICK TECHNOLOGIES - Note List Creator ID"	Keyword="?"			Name="?"
(0021,0001) VERS="SCH"	VR="UI"   VM="1"	Owner="SCHICK TECHNOLOGIES - Change Item Creator ID"	Keyword="?"			Name="?"
(0021,0002) VERS="SCH"	VR="US"   VM="1"	Owner="SCHICK TECHNOLOGIES - Change Item Creator ID"	Keyword="?"			Name="?" 
(0021,0003) VERS="SCH"	VR="DT"   VM="1"	Owner="SCHICK TECHNOLOGIES - Change Item Creator ID"	Keyword="?"			Name="?"
(0021,0004) VERS="SCH"	VR="PN"   VM="1"	Owner="SCHICK TECHNOLOGIES - Change Item Creator ID"	Keyword="?"			Name="?"
(0021,0005) VERS="SCH"	VR="OB"   VM="1"	Owner="SCHICK TECHNOLOGIES - Change Item Creator ID"	Keyword="?"			Name="?"
(0021,0001) VERS="HOL"	VR="LT"   VM="1"	Owner="Hologic"	Keyword="ImageAnalysisDataInXML"	Name="Image Analysis Data in XML"
(0021,0001) VERS="HOL"	VR="LT"   VM="1"	Owner="HOLOGIC"	Keyword="ImageAnalysisDataInXML"	Name="Image Analysis Data in XML"
(0023,0000) VERS="HOL"	VR="LO"   VM="1"	Owner="Hologic"	Keyword="EncodingSchemeVersion"		Name="Encoding Scheme Version"
(0023,0000) VERS="HOL"	VR="LO"   VM="1"	Owner="HOLOGIC"	Keyword="EncodingSchemeVersion"		Name="Encoding Scheme Version"
(0023,0001) VERS="HOL"	VR="LO"   VM="1"	Owner="Hologic"	Keyword="PFileName"					Name="P File Name"
(0023,0001) VERS="HOL"	VR="LO"   VM="1"	Owner="HOLOGIC"	Keyword="PFileName"					Name="P File Name"
(0023,0002) VERS="HOL"	VR="OB"   VM="1"	Owner="Hologic"	Keyword="PFileData"					Name="P File Data"
(0023,0002) VERS="HOL"	VR="OB"   VM="1"	Owner="HOLOGIC"	Keyword="PFileData"					Name="P File Data"
(0023,0003) VERS="HOL"	VR="UL"   VM="1"	Owner="Hologic"	Keyword="PFileLength"				Name="P File Length"
(0023,0003) VERS="HOL"	VR="UL"   VM="1"	Owner="HOLOGIC"	Keyword="PFileLength"				Name="P File Length"
(0023,0004) VERS="HOL"	VR="OB"   VM="1"	Owner="Hologic"	Keyword="RFileData"					Name="R File Data"
(0023,0004) VERS="HOL"	VR="OB"   VM="1"	Owner="HOLOGIC"	Keyword="RFileData"					Name="R File Data"
(0023,0005) VERS="HOL"	VR="UL"   VM="1"	Owner="Hologic"	Keyword="RFileLength"				Name="R File Length"
(0023,0005) VERS="HOL"	VR="UL"   VM="1"	Owner="HOLOGIC"	Keyword="RFileLength"				Name="R File Length"
(0029,0000) VERS="AEG"	VR="US"   VM="1-n"	Owner="AEGIS_DICOM_2.00"	Keyword="?"			Name="?"
(0029,0001) VERS="SCH"	VR="UL"   VM="1"	Owner="SCHICK TECHNOLOGIES - Image Security Creator ID"	Keyword="?"			Name="?"
(0029,0020) VERS="DEX"	VR="LT"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0029,0021) VERS="DEX"	VR="ST"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0029,0022) VERS="DEX"	VR="ST"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0029,0023) VERS="DEX"	VR="ST"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0029,0024) VERS="DEX"	VR="LO"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0029,0025) VERS="DEX"	VR="LO"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0029,0026) VERS="DEX"	VR="LO"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0029,0027) VERS="DEX"	VR="LO"   VM="1"	Owner="2.16.840.1.114059.1.1.6.1.50.1"	Keyword="?"			Name="?"
(0073,0001) VERS="STE"  VR="ST"   VM="1"	Owner="STENTOR"	Keyword="?"			Name="?" 
(0073,0002) VERS="STE"  VR="ST"   VM="1"	Owner="STENTOR"	Keyword="?"			Name="?" 
(0073,0003) VERS="STE"  VR="ST"   VM="1"	Owner="STENTOR"	Keyword="?"			Name="?" 
(0087,0010) VERS="ARM"  VR="CS"   VM="1"	Owner="1.2.840.113708.794.1.1.2.0"	Keyword="MediaType"		Name="Media Type"
(0087,0020) VERS="ARM"  VR="CS"   VM="1"	Owner="1.2.840.113708.794.1.1.2.0"	Keyword="MediaLocation"		Name="Media Location"
(0087,0050) VERS="ARM"  VR="IS"   VM="1"	Owner="1.2.840.113708.794.1.1.2.0"	Keyword="EstimatedRetrieveTime"	Name="Estimated Retrieve Time"
(1369,0000) VERS="AEG"	VR="US"   VM="1-n"	Owner="AEGIS_DICOM_2.00"	Keyword="?"			Name="?"
(0009,0004) VERS="FUJ"  VR="SH"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageControlUnit"						Name="Image Control Unit"
(0009,0005) VERS="FUJ"  VR="OW"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageUID"								Name="Image UID"
(0009,0006) VERS="FUJ"  VR="OW"   VM="1"	Owner="FDMS 1.0"	Keyword="RouteImageUID"							Name="Route Image UID"
(0009,0008) VERS="FUJ"  VR="UL"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageDisplayInformationVersionNumber"	Name="Image Display Information Version Number"
(0009,0009) VERS="FUJ"  VR="UL"   VM="1"	Owner="FDMS 1.0"	Keyword="PatientInformationVersionNumber"		Name="Patient Information Version Number"
(0009,000C) VERS="FUJ"  VR="OW"   VM="1"	Owner="FDMS 1.0"	Keyword="FilmUID"								Name="Film UID"
(0009,0010) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ExposureUnitTypeCode"					Name="Exposure Unit Type Code"
(0009,0080) VERS="FUJ"  VR="LO"   VM="1"	Owner="FDMS 1.0"	Keyword="KanjiHospitalName"						Name="Kanji Hospital Name"
(0009,0090) VERS="FUJ"  VR="ST"   VM="1"	Owner="FDMS 1.0"	Keyword="DistributionCode"						Name="Distribution Code"
(0009,0092) VERS="FUJ"  VR="SH"   VM="1"	Owner="FDMS 1.0"	Keyword="KanjiDepartmentName"					Name="Kanji Department Name"
(0009,00F0) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="BlackeningProcessFlag"					Name="Blackening Process Flag"
(0009,00F1) VERS="FUJ"  VR="LO"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0019,0015) VERS="FUJ"  VR="LO"   VM="1"	Owner="FDMS 1.0"	Keyword="KanjiBodyPartForExposure"				Name="Kanji Body Part for Exposure"
(0019,0030) VERS="FUJ"  VR="LO"   VM="1"	Owner="FDMS 1.0"	Keyword="MenuCharacterString"					Name="Menu Character String"
(0019,0032) VERS="FUJ"  VR="LO"   VM="1"	Owner="FDMS 1.0"	Keyword="KanjiMenuName"							Name="Kanji Menu Name"
(0019,0040) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageProcessingType"					Name="Image Processing Type"
(0019,0050) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="EDRMode"								Name="EDR Mode"
(0019,0060) VERS="FUJ"  VR="SH"   VM="1"	Owner="FDMS 1.0"	Keyword="RadiographersCode"						Name="Radiographer's Code"
(0019,0070) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="SplitExposureFormat"					Name="Split Exposure Format"
(0019,0071) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="NumberOfSplitExposureFrames"			Name="Number of Split Exposure Frames"
(0019,0080) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="ReadingPositionSpecification"			Name="Reading Position Specification"
(0019,0081) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="ReadingSensitivityCenter"				Name="Reading Sensitivity Center"
(0019,0090) VERS="FUJ"  VR="SH"   VM="1"	Owner="FDMS 1.0"	Keyword="FilmAnnotationCharacterString1"		Name="Film Annotation Character String 1"
(0019,0091) VERS="FUJ"  VR="SH"   VM="1"	Owner="FDMS 1.0"	Keyword="FilmAnnotationCharacterString2"		Name="Film Annotation Character String 2"
(0021,0010) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="FCRImageID"							Name="FCR Image ID"
(0021,0030) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="SetNumber"								Name="Set Number"
(0021,0040) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageNumberInTheSet"					Name="Image Number in the Set"
(0021,0050) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="PairProcessingInformation"				Name="Pair Processing Information"
(0021,0070) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="FilmNumberWithinTheSeries"				Name="Film Number within the Series"
(0021,0080) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="EquipmentTypeSpecificInformation"		Name="Equipment Type-Specific Information"
(0021,0090) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="LUTNumber"								Name="LUT Number"
(0023,0010) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0023,0020) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0023,0030) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0010) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="RelativeLightEmissionAmountSk"			Name="Relative Light Emission Amount Sk"
(0025,0011) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="TermOfCorrectionForEachIPTypeSt"		Name="Term of Correction for Each IP Type St"
(0025,0012) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="ReadingGainGp"							Name="Reading Gain Gp"
(0025,0013) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0015) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0020) VERS="FUJ"  VR="US"   VM="2"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0021) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0030) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0030) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0031) VERS="FUJ"  VR="SS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0032) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0033) VERS="FUJ"  VR="SS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0034) VERS="FUJ"  VR="SS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0040) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0041) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0042) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0042) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0043) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0050) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0051) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0052) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0053) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0060) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0061) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0062) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0063) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0070) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0071) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0072) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0072) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0073) VERS="FUJ"  VR="US"   VM="6"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0074) VERS="FUJ"  VR="US"   VM="6"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0080) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0081) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0081) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0081) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0082) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0082) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0082) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0083) VERS="FUJ"  VR="US"   VM="6"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0083) VERS="FUJ"  VR="US"   VM="6"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0084) VERS="FUJ"  VR="US"   VM="6"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0084) VERS="FUJ"  VR="US"   VM="6"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0084) VERS="FUJ"  VR="US"   VM="6"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0090) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0091) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0092) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0093) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0094) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0095) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,0096) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a0) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a0) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a0) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a1) VERS="FUJ"  VR="SS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a1) VERS="FUJ"  VR="SS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a2) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a2) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a3) VERS="FUJ"  VR="SS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0025,00a3) VERS="FUJ"  VR="SS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,0010) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,0020) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,0030) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,0040) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,0050) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,0060) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,0070) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,0080) VERS="FUJ"  VR="SQ"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?" 
(0027,00a0) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a0) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a0) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a0) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a0) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a0) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a1) VERS="FUJ"  VR="CS"   VM="2"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a1) VERS="FUJ"  VR="CS"   VM="2"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a2) VERS="FUJ"  VR="CS"   VM="2"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a2) VERS="FUJ"  VR="CS"   VM="2"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a2) VERS="FUJ"  VR="CS"   VM="2"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a3) VERS="FUJ"  VR="SS"   VM="1-n"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a3) VERS="FUJ"  VR="SS"   VM="1-n"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a3) VERS="FUJ"  VR="SS"   VM="1-n"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a3) VERS="FUJ"  VR="SS"   VM="1-n"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a3) VERS="FUJ"  VR="SS"   VM="1-n"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a3) VERS="FUJ"  VR="SS"   VM="1-n"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0027,00a3) VERS="FUJ"  VR="SS"   VM="1-n"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(0029,0020) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageScanningDirection"				Name="Image Scanning Direction"
(0029,0025) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageRotationReversalInformation"		Name="Image Rotation/Reversal Information"
(0029,0030) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ExtendedReadingSizeValue"				Name="Extended Reading Size Value"
(0029,0034) VERS="FUJ"  VR="US"   VM="1"	Owner="FDMS 1.0"	Keyword="MagReducRatio"							Name="Mag./Reduc. Ratio"
(0029,0044) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="LineDensityCode"						Name="Line Density Code"
(0029,0050) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="DataCompressionCode"					Name="Data Compression Code"
(0032,0032) VERS="FUJ"  VR="PN"   VM="1"	Owner="FDMS 1.0"	Keyword="RequestingPhysician"					Name="Requesting Physician"
(0032,0033) VERS="FUJ"  VR="LO"   VM="1"	Owner="FDMS 1.0"	Keyword="RequestingService"						Name="Requesting Service"
(2011,0000) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="TrimDensity"							Name="Trim Density"
(2011,0001) VERS="FUJ"  VR="IS"   VM="1"	Owner="FDMS 1.0"	Keyword="TrimWidth"								Name="Trim Width"
(2011,0002) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageMagReducRatio"					Name="Image Mag./Reduc. Range"
(2011,0010) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageDisplayFormat"					Name="Image Display Format"
(2011,0011) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImagePositionSpecifyingFlag"			Name="Image Position Specifying Flag"
(2011,0020) VERS="FUJ"  VR="OW"   VM="1"	Owner="FDMS 1.0"	Keyword="InterpolationAVRSSystemFormat"			Name="Interpolation A-VRS System Format"
(50F1,0006) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="EnergySubtractionParameter"			Name="Energy Subtraction Parameter"
(50F1,0007) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="SubtractionRegistrationResult"			Name="Subtraction Registration Result"
(50F1,0008) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="EnergySubtractionParameter2"			Name="Energy Subtraction Parameter 2"
(50F1,0009) VERS="FUJ"  VR="SL"   VM="1"	Owner="FDMS 1.0"	Keyword="AfinConversionCoefficient"				Name="Afin Conversion Coefficient"
(50F1,000A) VERS="FUJ"  VR="LO"   VM="1"	Owner="FDMS 1.0"	Keyword="?"										Name="?"
(50F1,0010) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="FilmOutputFormat"						Name="Film Output Format"
(50F1,0020) VERS="FUJ"  VR="CS"   VM="1"	Owner="FDMS 1.0"	Keyword="ImageProcessingModificationFlag"		Name="Image Processing Modification Flag"

(0019,0010) VERS="CAN"  VR="UN"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,0013) VERS="CAN"  VR="UN"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,0015) VERS="CAN"  VR="DS"   VM="2"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,0016) VERS="CAN"  VR="UN"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,0017) VERS="CAN"  VR="DS"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,0018) VERS="CAN"  VR="UN"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,0019) VERS="CAN"  VR="UN"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,001a) VERS="CAN"  VR="UN"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,001b) VERS="CAN"  VR="LO"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,001c) VERS="CAN"  VR="IS"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,001e) VERS="CAN"  VR="IS"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,001f) VERS="CAN"  VR="UN"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"
(0019,0021) VERS="CAN"  VR="IS"   VM="1"	Owner="Canon Inc."	Keyword="?"		Name="?"

(0019,0002) VERS="ADAC" VR="IS"   VM="1"	Owner="ADAC_IMG"	Keyword="ADACPegasysFileSize"		Name="ADAC Pegasys File Size"
(0019,0021) VERS="ADAC" VR="US"   VM="1"	Owner="ADAC_IMG"	Keyword="NumberOfADACHeaders"		Name="Number of ADAC Headers"
(0019,0041) VERS="ADAC" VR="IS"   VM="1-n"	Owner="ADAC_IMG"	Keyword="ADACHeaderImageSize"		Name="ADAC Header/Image Size"
(0019,0061) VERS="ADAC" VR="OB"   VM="1"	Owner="ADAC_IMG"	Keyword="ADACPegasysHeaders"		Name="ADAC Pegasys Headers"

(0009,0001) VERS="SEC"  VR="SH"   VM="1"	Owner="SECTRA_Ident_01"			Keyword="RequestNumber"		Name="Request number"
(0009,0002) VERS="SEC"  VR="SH"   VM="1"	Owner="SECTRA_Ident_01"			Keyword="ExaminationNumber"	Name="Examination number"
(0009,0004) VERS="SEC"  VR="LO"   VM="1"	Owner="SECTRA_Ident_01"			Keyword="SeriesIdentifier"	Name="Series Identifier"
(0009,0005) VERS="SEC"  VR="LO"   VM="1"	Owner="SECTRA_Ident_01"			Keyword="SeriesOrder"		Name="Series Order"
(0009,0006) VERS="SEC"  VR="LO"   VM="1"	Owner="SECTRA_Ident_01"			Keyword="FileName"			Name="File Name"
(0009,0007) VERS="SEC"  VR="LO"   VM="1"	Owner="SECTRA_Ident_01"			Keyword="ImageDataID"		Name="Image Data ID"
(0029,0001) VERS="SEC"  VR="OB"   VM="1"	Owner="SECTRA_ImageInfo_01"		Keyword="ImageInfo"			Name="Image info"
(0029,0002) VERS="SEC"  VR="CS"   VM="1"	Owner="SECTRA_ImageInfo_01"		Keyword="Marking"			Name="Marking"
(0029,0003) VERS="SEC"  VR="LO"   VM="1"	Owner="SECTRA_ImageInfo_01"		Keyword="NoDecompression"	Name="No decompression"
(0029,0004) VERS="SEC"  VR="OB"   VM="1"	Owner="SECTRA_ImageInfo_01"		Keyword="ImageInfoNew"		Name="Image info new"
(6001,0001) VERS="SEC"  VR="LO"   VM="1"	Owner="SECTRA_OverlayInfo_01"	Keyword="SectraOverlay"		Name="Sectra Overlay"

(0009,0000) VERS="BIO"  VR="LO"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0001) VERS="BIO"  VR="UN"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0002) VERS="BIO"  VR="UN"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0003) VERS="BIO"  VR="LO"   VM="1-n"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0004) VERS="BIO"  VR="LO"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0005) VERS="BIO"  VR="LO"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0007) VERS="BIO"  VR="LO"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0008) VERS="BIO"  VR="LO"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0009) VERS="BIO"  VR="LO"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"
(0009,0010) VERS="BIO"  VR="UN"   VM="1"	Owner="BioPri"			Keyword="?"		Name="?"

(0029,0013) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0014) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0017) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0018) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0019) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,001a) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,001b) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,001c) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,001d) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,001e) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0027) VERS="ISG"  VR="US"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0028) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0030) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0032) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0034) VERS="ISG"  VR="UN"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0035) VERS="ISG"  VR="CS"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"
(0029,0036) VERS="ISG"  VR="US"   VM="1"	Owner="Silhouette VRS 3.0"		Keyword="?"			Name="?"

(0019,0006) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="PaddleID"			Name="Paddle ID"
(0019,0007) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="PaddlePosition"	Name="Paddle Position"
(0019,0008) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="CollimationSize"	Name="Collimation Size"
(0019,0026) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0027) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0028) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0029) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0030) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0031) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0032) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0033) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0034) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0035) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0040) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0041) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0050) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0051) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0052) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0053) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0070) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"
(0019,0071) VERS="LOR"  VR="OB"   VM="1"	Owner="LORAD Selenia"		Keyword="?"					Name="?"

(0019,0006) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0007) VERS="HOL"  VR="SH"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0008) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0016) VERS="HOL"  VR="DS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0026) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0027) VERS="HOL"  VR="SH"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0028) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0029) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0030) VERS="HOL"  VR="US"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0031) VERS="HOL"  VR="US"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0032) VERS="HOL"  VR="US"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0033) VERS="HOL"  VR="US"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0034) VERS="HOL"  VR="US"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0035) VERS="HOL"  VR="US"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0037) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0040) VERS="HOL"  VR="DS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0041) VERS="HOL"  VR="DS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0042) VERS="HOL"  VR="IS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0043) VERS="HOL"  VR="IS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0044) VERS="HOL"  VR="IS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?" 
(0019,0045) VERS="HOL"  VR="IS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?" 
(0019,0046) VERS="HOL"  VR="IS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0070) VERS="HOL"  VR="DS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0085) VERS="HOL"  VR="IS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(0019,0090) VERS="HOL"  VR="DS"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"

(7e01,0001) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(7e01,0002) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(7e01,0010) VERS="HOL"  VR="SQ"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(7e01,0011) VERS="HOL"  VR="SQ"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(7e01,0012) VERS="HOL"  VR="OB"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"

(7f01,0001) VERS="HOL"  VR="LO"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(7f01,0002) VERS="HOL"  VR="SH"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(7f01,0010) VERS="HOL"  VR="SQ"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"
(7f01,0012) VERS="HOL"  VR="OB"   VM="1"	Owner="HOLOGIC, Inc."		Keyword="?"					Name="?"

(0029,0000) VERS="ATL"  VR="US"   VM="1"	Owner="1.2.840.113663.1"			Keyword="?"		Name="?"
(0029,0001) VERS="ATL"  VR="US"   VM="1"	Owner="1.2.840.113663.1"			Keyword="?"		Name="?"

(0009,0048) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0009,004e) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0011,0001) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0001) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0002) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0003) VERS="HIT"  VR="SH"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0004) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0005) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0008) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0009) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,000a) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,000b) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,000c) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,000f) VERS="HIT"  VR="IS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0019,0010) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0001) VERS="HIT"  VR="IS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0002) VERS="HIT"  VR="IS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0005) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0006) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0008) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0009) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,000a) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,000b) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,000c) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,000d) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,000e) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,000f) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0010) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0011) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0012) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0013) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0014) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0015) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0016) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0017) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0018) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,001c) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0020) VERS="HIT"  VR="IS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0021) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0022) VERS="HIT"  VR="ST"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0023) VERS="HIT"  VR="LO"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0024) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0025) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0026) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0027) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0028) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,0029) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,002a) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,002b) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,002c) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,002d) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,002e) VERS="HIT"  VR="DS"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"
(0029,002f) VERS="HIT"  VR="OB"   VM="1"	Owner="MMCPrivate"			Keyword="?"		Name="?"

(0019,0001) VERS="MEV"  VR="LO"   VM="1"	Owner="MeVis BreastCare"	Keyword="?"		Name="?"
(0071,0001) VERS="MEV"  VR="LO"   VM="1"	Owner="MeVis BreastCare"	Keyword="?"		Name="?"

(0065,0093) VERS=""     VR="CS"   VM="1"	Owner="Viewing Protocol"	Keyword="?"		Name="?"

(1455,0000) VERS="MOR"  VR="OW"   VM="1"	Owner="Mortara_Inc"			Keyword="ELIInterpretationVector"		Name="ELI Interpretation Vector"
(1455,0001) VERS="MOR"  VR="UN"   VM="1"	Owner="Mortara_Inc"			Keyword="CustomID"						Name="Custom ID"
(1455,0002) VERS="MOR"  VR="UT"   VM="1"	Owner="Mortara_Inc"			Keyword="Race"							Name="Race"
(1455,0003) VERS="MOR"  VR="UT"   VM="1"	Owner="Mortara_Inc"			Keyword="SocialSecurityNumber"			Name="Social Security Number"
(1455,0004) VERS="MOR"  VR="UT"   VM="1"	Owner="Mortara_Inc"			Keyword="AttendingPhysician"			Name="Attending Physician"
(1455,0005) VERS="MOR"  VR="UT"   VM="1"	Owner="Mortara_Inc"			Keyword="Procedural Diagnosis"			Name="ProceduralDiagnosis"
(1455,0006) VERS="MOR"  VR="UT"   VM="1"	Owner="Mortara_Inc"			Keyword="Note1"							Name="Note 1"
(1455,0007) VERS="MOR"  VR="UT"   VM="1"	Owner="Mortara_Inc"			Keyword="Note2"							Name="Note 2"
(1455,0008) VERS="MOR"  VR="LO"   VM="1"	Owner="Mortara_Inc"			Keyword="OrderRequestNumber"			Name="Order Request Number"
(1455,0010) VERS="MOR"  VR="LO"   VM="1"	Owner="Mortara_Inc"			Keyword="ManufacturerName"				Name="Manufacturer Name"

(0031,0098) VERS=""		VR="OW"   VM="1"	Owner="SEGAMI MIML"			Keyword="?"		Name="?"

(1269,0001) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyImage"				Name="Biopsy Image"
(1269,0010) VERS="IMS"  VR="IS"   VM="1-n"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyMarkersX"			Name="Biopsy Markers X"
(1269,0011) VERS="IMS"  VR="IS"   VM="1-n"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyMarkersY"			Name="Biopsy Markers Y"
(1269,0012) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyMarkersNumber"		Name="Biopsy Markers Number"
(1269,0020) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyAreaLeftBorder"		Name="Biopsy Area Left Border"
(1269,0021) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyAreaRightBorder"		Name="Biopsy Area Right Border"
(1269,0022) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyAreaTopBorder"		Name="Biopsy Area Top Border"
(1269,0023) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Biopsy Private Code"				Keyword="BiopsyAreaBottomBorder"	Name="Biopsy Area Bottom Border"

(1271,0001) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0002) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0010) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0011) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0012) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0013) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0020) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0021) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0022) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0038) VERS="IMS"  VR="LO"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0039) VERS="IMS"  VR="US"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0040) VERS="IMS"  VR="US"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0041) VERS="IMS"  VR="LO"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0042) VERS="IMS"  VR="LT"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0045) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0046) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0047) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0048) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0049) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0050) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0051) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0052) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0053) VERS="IMS"  VR="LO"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"
(1271,0054) VERS="IMS"  VR="IS"   VM="1"	Owner="IMS s.r.l. Mammography Private Code"			Keyword="?"		Name="?"

(5473,0003) VERS=""     VR="LO"   VM="1"	Owner="MedIns HP Extensions"			Keyword="?"		Name="?"

(0029,0001) VERS=""     VR="UL"   VM="1"	Owner="MEDIFACE"			Keyword="?"		Name="?"
(0029,0010) VERS=""     VR="DS"   VM="1"	Owner="MEDIFACE"			Keyword="?"		Name="?"
(0029,0011) VERS=""     VR="DS"   VM="1"	Owner="MEDIFACE"			Keyword="?"		Name="?"
(0029,0020) VERS=""     VR="DS"   VM="1"	Owner="MEDIFACE"			Keyword="?"		Name="?"
(0029,0021) VERS=""     VR="UL"   VM="1"	Owner="MEDIFACE"			Keyword="?"		Name="?"
(0029,0022) VERS=""     VR="DS"   VM="2"	Owner="MEDIFACE"			Keyword="?"		Name="?"
(0029,0030) VERS=""     VR="LT"   VM="1"	Owner="MEDIFACE"			Keyword="?"		Name="?"

(8003,0000) VERS=""     VR="LO"   VM="1"	Owner="Image (ID, Version, Size, Dump, GUID)"			Keyword="ID"		Name="ID"
(8003,0010) VERS=""     VR="LO"   VM="1"	Owner="Image (ID, Version, Size, Dump, GUID)"			Keyword="Version"	Name="Version"
(8003,0020) VERS=""     VR="UL"   VM="1"	Owner="Image (ID, Version, Size, Dump, GUID)"			Keyword="Size"		Name="Size"
(8003,0030) VERS=""     VR="OB"   VM="1"	Owner="Image (ID, Version, Size, Dump, GUID)"			Keyword="Dump"		Name="Dump"
(8003,0040) VERS=""     VR="LO"   VM="1"	Owner="Image (ID, Version, Size, Dump, GUID)"			Keyword="GUID"		Name="GUID"
(8101,0000) VERS=""     VR="LO"   VM="1"	Owner="ObjectModel (ID, Version, Place, PlaceDescription)"			Keyword="ID"		Name="ID"
(8101,0010) VERS=""     VR="LO"   VM="1"	Owner="ObjectModel (ID, Version, Place, PlaceDescription)"			Keyword="Version"	Name="Version"

(0015,0010) VERS=""     VR="LO"   VM="1"	Owner="INFINITT_FMX"			Keyword="?"		Name="?"
(0015,0011) VERS=""     VR="LO"   VM="1"	Owner="INFINITT_FMX"			Keyword="?"		Name="?"

(0009,0001) VERS=""     VR="LO"   VM="1"	Owner="BrainLAB_Conversion"			Keyword="ExportPlatformName"			Name="Export Platform Name" 
(0009,0002) VERS=""     VR="OB"   VM="1"	Owner="BrainLAB_Conversion"			Keyword="ExportPlatformData"			Name="Export Platform Data"

(3273,0000) VERS=""     VR="DS"   VM="3"	Owner="BrainLAB_PatientSetup"		Keyword="IsocenterPosition"				Name="Isocenter Position" 
(3273,0001) VERS=""     VR="CS"   VM="1"	Owner="BrainLAB_PatientSetup"		Keyword="PatientPosition"				Name="Patient Position" 

(3411,0001) VERS=""     VR="SQ"   VM="1"	Owner="BrainLAB_BeamProfile"		Keyword="BeamProfileSequence"			Name="Beam Profile Sequence" 
(3411,0002) VERS=""     VR="IS"   VM="1"	Owner="BrainLAB_BeamProfile"		Keyword="BeamProfileNumber"				Name="Beam Profile Number" 
(3411,0003) VERS=""     VR="SQ"   VM="1"	Owner="BrainLAB_BeamProfile"		Keyword="BeamParameterSequence"			Name="Beam Parameter Sequence" 
(3411,0004) VERS=""     VR="UT"   VM="1"	Owner="BrainLAB_BeamProfile"		Keyword="ParameterDescription"			Name="Parameter Description" 
(3411,0005) VERS=""     VR="OB"   VM="1"	Owner="BrainLAB_BeamProfile"		Keyword="ParameterData"					Name="Parameter Data" 
(3411,0006) VERS=""     VR="IS"   VM="1"	Owner="BrainLAB_BeamProfile"		Keyword="ReferencedBeamProfileNumber"	Name="Referenced Beam Profile Number"

(0011,0001) VERS=""     VR="OB"   VM="1"	Owner="V1"			Keyword="UserData"						Name="User Data"
(0011,0002) VERS=""     VR="DS"   VM="1"	Owner="V1"			Keyword="NormalizationCoefficient"		Name="Normalization Coefficient"
(0011,0003) VERS=""     VR="DS"   VM="1-n"	Owner="V1"			Keyword="ReceivingGain"					Name="Receiving Gain"
(0011,0004) VERS=""     VR="DS"   VM="1"	Owner="V1"			Keyword="MeanImageNoise"				Name="Mean Image Noise"

(1135,0000) VERS=""     VR="UI"   VM="1"	Owner="Voxar 2.16.124.113543.6003.1999.12.20.12.5.0"			Keyword="?"		Name="?"
(1135,0001) VERS=""     VR="OB"   VM="1"	Owner="Voxar 2.16.124.113543.6003.1999.12.20.12.5.0"			Keyword="?"		Name="?"
(1135,0002) VERS=""     VR="SQ"   VM="1"	Owner="Voxar 2.16.124.113543.6003.1999.12.20.12.5.0"			Keyword="?"		Name="?"
(1135,0006) VERS=""     VR="UL"   VM="1"	Owner="Voxar 2.16.124.113543.6003.1999.12.20.12.5.0"			Keyword="?"		Name="?"
(1135,0007) VERS=""     VR="UI"   VM="1"	Owner="Voxar 2.16.124.113543.6003.1999.12.20.12.5.0"			Keyword="?"		Name="?"
(1135,0008) VERS=""     VR="SQ"   VM="1"	Owner="Voxar 2.16.124.113543.6003.1999.12.20.12.5.0"			Keyword="?"		Name="?"
(1135,0013) VERS=""     VR="LO"   VM="1"	Owner="Voxar 2.16.124.113543.6003.1999.12.20.12.5.0"			Keyword="?"		Name="?"

(0029,0015) VERS=""     VR="LO"   VM="1"	Owner="Kodak Image Information"			Keyword="?"		Name="?"
(0029,0016) VERS=""     VR="LO"   VM="1"	Owner="Kodak Image Information"			Keyword="?"		Name="?"
(0029,0017) VERS=""     VR="LO"   VM="1"	Owner="Kodak Image Information"			Keyword="?"		Name="?"
(0029,0018) VERS=""     VR="UT"   VM="1"	Owner="Kodak Image Information"			Keyword="?"		Name="?"
(0029,0019) VERS=""     VR="IS"   VM="1"	Owner="Kodak Image Information"			Keyword="?"		Name="?"
(0029,001a) VERS=""     VR="IS"   VM="1"	Owner="Kodak Image Information"			Keyword="?"		Name="?"

(0037,0001) VERS=""     VR="LO"   VM="1"	Owner="MAROTECH Inc."			Keyword="?"		Name="?"
(0037,0021) VERS=""     VR="US"   VM="1"	Owner="MAROTECH Inc."			Keyword="?"		Name="?"
(0037,0022) VERS=""     VR="US"   VM="1"	Owner="MAROTECH Inc."			Keyword="?"		Name="?"
(0037,0023) VERS=""     VR="OB"   VM="1"	Owner="MAROTECH Inc."			Keyword="?"		Name="?"

(0021,0000) VERS=""     VR="SQ"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonInformationSequence"	Name="Person Information Sequence"
(0021,0001) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonID"					Name="Person ID"
(0021,0002) VERS=""     VR="PN"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonName"				Name="Person Name"
(0021,0003) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonRole"				Name="Person Role"
(0021,0004) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonHomePhone"			Name="Person Home Phone"
(0021,0005) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonWorkPhone"			Name="Person Work Phone"
(0021,0006) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonCellPhone"			Name="Person Cell Phone"
(0021,0007) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonPagerPhone"			Name="Person Pager Phone"
(0021,0008) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonFaxPhone"			Name="Person Fax Phone"
(0021,0009) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonEMail"				Name="Person EMail"
(0021,000A) VERS=""     VR="ST"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonAddress"				Name="Person Address"
(0021,000B) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonPassword"			Name="Person Password"
(0021,000C) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PersonEmergencyPhone"		Name="Person Emergency Phone"
(0021,000D) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PhysicianID"				Name="Physician ID"
(0021,0011) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="OriginalPatientID"			Name="Original Patient ID"
(0021,0012) VERS=""     VR="UI"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="OriginalStudyInstanceUID"	Name="Original Study Instance UID"
(0021,0013) VERS=""     VR="UI"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="OriginalSeriesInstanceUID"	Name="Original Series Instance UID"
(0021,0014) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="MasterAccessionNumber"		Name="Master Accession Number"
(0021,0015) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="OrderCategory"				Name="Order Category"
(0021,0016) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PatientICN"				Name="Patient ICN"
(0021,0017) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PatientDFS"				Name="Patient DFS"
(0021,0018) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PatientClass"				Name="Patient Class"
(0021,0019) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="PatientType"				Name="Patient Type"
(0021,001F) VERS=""     VR="LT"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="GenericString"				Name="Generic String"
(0021,0020) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCStudyAssignedBy"			Name="QC Study Assigned By"
(0021,0021) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCStudySplitBy"			Name="QC Study Split By"
(0021,0022) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCStudyMovedBy"			Name="QC Study Moved By"
(0021,0023) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCStudyEditedBy"			Name="QC Study Edited By"
(0021,0024) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCSeriesSplitBy"			Name="QC Series Split By"
(0021,0025) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCSeriesMovedBy"			Name="QC Series Moved By"
(0021,0026) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCSeriesEditedBy"			Name="QC Series Edited By"
(0021,0027) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCImageMovedBy"			Name="QC Image Moved By"
(0021,0028) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCImageEditedBy"			Name="QC Image Edited By"
(0021,0030) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCDoneTime"				Name="QC Done Time"
(0021,0031) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCLastModificationTime"	Name="QC Last Modification Time"
(0021,0032) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCImageAcceptedBy"			Name="QC Image Accepted By"
(0021,0033) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCImageRejectedBy"			Name="QC Image Rejected By"
(0021,0034) VERS=""     VR="DA"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCDoneDate"				Name="QC Done Date"
(0021,0034) VERS=""     VR="DA"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCLastModificationDate"	Name="QC Last Modification Date"
(0021,0050) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="QCDeletionRequested"		Name="QC Deletion Requested"
(0021,0090) VERS=""     VR="AE"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="OriginalSenderAETitle"		Name="Original Sender AE Title"
(0021,0091) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="SoftwareTitle"				Name="Software Title"
(0021,0092) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="SoftwareVersion"			Name="Software Version"
(0021,0093) VERS=""     VR="LO"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="SerialNumber"				Name="Serial Number"
(0021,00a0) VERS=""     VR="SQ"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="ObjectActionSequence"		Name="Object Action Sequence"
(0021,00a1) VERS=""     VR="ST"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="ObjectAction"				Name="Object Action"
(0021,00a2) VERS=""     VR="DA"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="ObjectActionDate"			Name="Object Action Date"
(0021,00a3) VERS=""     VR="TM"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="ObjectActionTime"			Name="Object Action Time"
(0021,00a5) VERS=""     VR="AE"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="LocalAETitle"				Name="Local AE Title"
(0021,00a6) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="LocalIPAddress"			Name="Local IP Address"
(0021,00a7) VERS=""     VR="AE"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="RemoteAETitle"				Name="Remote AE Title"
(0021,00a8) VERS=""     VR="SH"   VM="1"	Owner="BRIT Systems, Inc."	Keyword="RemoteIPAddress"			Name="Remote IP Address"

(3005,0000) VERS=""     VR="SQ"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,0002) VERS=""     VR="CS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,0004) VERS=""     VR="DS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,0006) VERS=""     VR="DS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,0008) VERS=""     VR="DS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,000a) VERS=""     VR="CS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,000c) VERS=""     VR="CS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,000e) VERS=""     VR="CS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,0010) VERS=""     VR="DS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"
(3005,0012) VERS=""     VR="DS"   VM="1"	Owner="MDS NORDION OTP ANATOMY MODELLING"	Keyword="?"			Name="?"

(4321,0041) VERS=""     VR="CS"   VM="1"	Owner="Imaging Dynamics Company Ltd."	Keyword="?"			Name="?" 
(4321,0042) VERS=""     VR="US"   VM="1"	Owner="Imaging Dynamics Company Ltd."	Keyword="?"			Name="?" 
(4321,0064) VERS=""     VR="LO"   VM="1"	Owner="Imaging Dynamics Company Ltd."	Keyword="PODMode"			Name="POD Mode" 

(f001,0000) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="PatientSpecies"			Name="Patient Species"
(f001,0001) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="PatientBreed"				Name="Patient Breed"
(f001,0002) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="PatientCategorySize"		Name="Patient Category Size"
(f001,0003) VERS=""     VR="CS"   VM="1"	Owner="Sound Technologies"	Keyword="PatientSexExtended"		Name="Patient Sex Extended"
(f001,0004) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ImageView"					Name="Image View"
(f001,0005) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="AnatomyImaged"				Name="Anatomy Imaged"
(f001,0006) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ImageEnhancements"			Name="Image Enhancements"
(f001,0007) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="DetectorSettings"			Name="Detector Settings"
(f001,0008) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ApplicationVersion"		Name="Application Version"
(f001,0009) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ImageLateralityExtended"	Name="Image Laterality Extended"
(f001,000a) VERS=""     VR="PN"   VM="1"	Owner="Sound Technologies"	Keyword="ClientName"				Name="Client Name"
(f001,000b) VERS=""     VR="UI"   VM="1"	Owner="Sound Technologies"	Keyword="ReferenceStudyInstanceUID"	Name="Reference Study Instance UID"
(f001,000c) VERS=""     VR="UI"   VM="1"	Owner="Sound Technologies"	Keyword="ReferenceStudyInstanceUID"	Name="Reference Study Instance UID"
(f001,000d) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ExamRefID"					Name="Exam Ref ID"
(f001,000e) VERS=""     VR="ST"   VM="1"	Owner="Sound Technologies"	Keyword="PhysicianOfRecordAddress"	Name="Physician of Record Address"
(f001,000f) VERS=""     VR="SH"   VM="1"	Owner="Sound Technologies"	Keyword="PhysicianOfRecordPhoneNumbers"	Name="Physician of Record Phone Numbers"
(f001,0010) VERS=""     VR="LT"   VM="1"	Owner="Sound Technologies"	Keyword="ReasonForStudy"			Name="Reason For Study"
(f001,0011) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="Protocol"					Name="Protocol"
(f001,0012) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="CaptureInputType"			Name="Capture Input Type"
(f001,0013) VERS=""     VR="LT"   VM="1"	Owner="Sound Technologies"	Keyword="ExamComplaint"				Name="Exam Complaint"
(f001,0014) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ExamWebCode"				Name="Exam Web Code"
(f001,0015) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ExamCategory"				Name="Exam Category"
(f001,0016) VERS=""     VR="SH"   VM="1"	Owner="Sound Technologies"	Keyword="ExamDiagnosis"				Name="Exam Diagnosis"
(f001,0017) VERS=""     VR="PN"   VM="1"	Owner="Sound Technologies"	Keyword="ExamCreatedBy"				Name="Exam Created By"
(f001,0018) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ExamCreatedByGroup"		Name="Exam Created By Group"
(f001,0019) VERS=""     VR="DT"   VM="1"	Owner="Sound Technologies"	Keyword="ExamRequiredByDateTime"	Name="Exam Required By DateTime"
(f001,001a) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="CaptureType"				Name="Capture Type"
(f001,001b) VERS=""     VR="IS"   VM="1"	Owner="Sound Technologies"	Keyword="TelemedExamID"				Name="Telemed Exam ID"
(f001,001c) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ExamCreatedByGuid"			Name="Exam Created By Guid"
(f001,001d) VERS=""     VR="LO"   VM="1"	Owner="Sound Technologies"	Keyword="ClientNameGuid"			Name="Client Name Guid"

(3711,000c) VERS=""     VR="UI"   VM="1"	Owner="A.L.I. Technologies, Inc."	Keyword="?"			Name="?"

(7777,0002) VERS=""     VR="UT"   VM="1"	Owner="NUD_PRIVATE"			Keyword="Interfile"			Name="Interfile"
(7777,0005) VERS=""     VR="IS"   VM="1"	Owner="NUD_PRIVATE"			Keyword="?"					Name="?"

(0011,0000) VERS=""     VR="LO"   VM="1"	Owner="IDEXX"	Keyword="Breed Name"			Name="Breed Name"
(0011,0001) VERS=""     VR="LO"   VM="1"	Owner="IDEXX"	Keyword="Species Name"			Name="Species Name"
(0011,0002) VERS=""     VR="PN"   VM="1"	Owner="IDEXX"	Keyword="Owner"					Name="Owner"

(0009,0001) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="EventTimerSequence"							Name="Event Timer Sequence"
(0009,0002) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="EventTimeInterval"								Name="Event Time Interval"
(0009,0003) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="EventCodeSequence"								Name="Event Code Sequence"
(0019,0001) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="FocusDepth"									Name="Focus Depth(s)"
(0019,0003) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="ExcludedIntervalsSequence"						Name="Excluded Intervals Sequence"
(0019,0004) VERS="SUP43"     VR="DT"   VM="1"	Owner="WG12 Supplement 43"			Keyword="ExclusionStartDatetime"						Name="Exclusion Start Datetime"
(0019,0005) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="ExclusionDuration"								Name="Exclusion Duration"
(0019,0006) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="USImageDescriptionSequence"					Name="US Image Description Sequence"
(0019,0007) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="ImageDataTypeSequence"							Name="Image Data Type Sequence"
(0019,0008) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="DataType"										Name="Data Type"
(0019,0009) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="TransducerScanGeometryCodeSequence"			Name="Transducer Scan Geometry Code Sequence"
(0019,000B) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="AliasedDataType"								Name="Aliased Data Type"
(0019,000C) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="PositionMeasuringDeviceUsed"					Name="Position Measuring Device Used"
(0019,000D) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="TransducerScanningConfigurationCodeSequence"	Name="Transducer Scanning Configuration Code Sequence"
(0019,000E) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="TransducerBeamSteeringCodeSequence"			Name="Transducer Beam Steering Code Sequence"
(0019,000F) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="TransducerAccessCodeSequence"					Name="Transducer Access Code Sequence"
(0021,0001) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="ImagePositionVolume"							Name="Image Position (Volume)"
(0021,0002) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="ImageOrientationVolume"						Name="Image Orientation (Volume)"
(0021,0007) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="UltrasoundAcquisitionGeometry"					Name="Ultrasound Acquisition Geometry"
(0021,0008) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="ApexPosition"									Name="Apex Position"
(0021,0009) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="VolumeToTransducerMappingMatrix"				Name="Volume to Transducer Mapping Matrix"
(0021,000A) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="VolumeToTableMappingMatrix"					Name="Volume to Table Mapping Matrix"
(0021,000C) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="PatientFrameOfReferenceSource"					Name="Patient Frame of Reference Source"
(0021,000D) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="TemporalPositionTimeOffset"					Name="Temporal Position Time Offset"
(0021,000E) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="PlanePositionVolumeSequence"					Name="Plane Position (Volume) Sequence"
(0021,000F) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="PlaneOrientationVolumeSequence"				Name="Plane Orientation (Volume) Sequence"
(0021,0010) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="TemporalPositionSequence"						Name="Temporal Position Sequence"
(0021,0011) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="DimensionOrganizationType"						Name="Dimension Organization Type"
(0029,0001) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="DataFrameAssignmentSequence"					Name="Data Frame Assignment Sequence"
(0029,0002) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="DataPathAssignment"							Name="Data Path Assignment"
(0029,0003) VERS="SUP43"     VR="US"   VM="1"	Owner="WG12 Supplement 43"			Keyword="BitsMappedToColorLookupTable"					Name="Bits Mapped to Color Lookup Table"
(0029,0004) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="Opacity1LUTSequence"							Name="Opacity 1 LUT Sequence"
(0029,0005) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="Opacity1LUTTransferFunction"					Name="Opacity 1 LUT Transfer Function"
(0029,0006) VERS="SUP43"     VR="FD"   VM="1"	Owner="WG12 Supplement 43"			Keyword="OpacityConstant"								Name="Opacity Constant"
(0029,0007) VERS="SUP43"     VR="US"   VM="1"	Owner="WG12 Supplement 43"			Keyword="OpacityLookupTableDescriptor"					Name="Opacity Lookup Table Descriptor"
(0029,0008) VERS="SUP43"     VR="OW"   VM="1"	Owner="WG12 Supplement 43"			Keyword="OpacityLookupTableData"						Name="Opacity Lookup Table Data"
(0029,000B) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="EnhancedPaletteColorLookupTableSequence"		Name="Enhanced Palette Color Lookup Table Sequence"
(0029,000C) VERS="SUP43"     VR="SQ"   VM="1"	Owner="WG12 Supplement 43"			Keyword="Opacity2LUTSequence"							Name="Opacity 2 LUT Sequence"
(0029,000D) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="Opacity2LUTTransferFunction"					Name="Opacity 2 LUT Transfer Function"
(0029,000E) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="DataPathID"									Name="Data Path ID"
(0029,000F) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="RGBLUTTransferFunction"						Name="RGB LUT Transfer Function"
(0029,0010) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="AlphaLUTTransferFunction"						Name="Alpha LUT Transfer Function"
(0041,0001) VERS="SUP43"     VR="CS"   VM="1"	Owner="WG12 Supplement 43"			Keyword="PerformedProtocolType"							Name="Performed Protocol Type"

(0009,0000) VERS="HIT"     VR="OB"   VM="1"	Owner="HMC - CT - ID"	Keyword="?"		Name="?"
(0009,0001) VERS="HIT"     VR="OB"   VM="1"	Owner="HMC - CT - ID"	Keyword="?"		Name="?"
(0019,0000) VERS="HIT"     VR="SH"   VM="1"	Owner="SET WINDOW"	Keyword="?"		Name="?"
(0019,0001) VERS="HIT"     VR="US"   VM="1"	Owner="SET WINDOW"	Keyword="?"		Name="?" 

(0017,0000) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="ExtendedBodyPart"				Name="Extended Body Part"
(0017,0010) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="ExtendedViewPosition"			Name="Extended View Position"
(0017,0020) VERS="SWS"     VR="SQ"   VM="1"	Owner="SVISION"	Keyword="ScheduledProcedureStepList"	Name="Scheduled Procedure Step List"
(0017,00a0) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="FixedGridSystem"				Name="Fixed Grid System"
(0017,00f0) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="ImagesSOPClass"				Name="Images SOP Class"

(0019,0000) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="AEC Field"
(0019,0001) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="AEC Film Screen"
(0019,0002) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="AEC Density"
(0019,0010) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Patient Thickness"
(0019,0016) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="?"
(0019,0018) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Beam Distance"
(0019,0020) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Workstation Number"
(0019,0028) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Tube Number"
(0019,0030) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Bucky Grid"
(0019,0034) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Focus"
(0019,0038) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Age Group"
(0019,0040) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Collimator Distance X"
(0019,0041) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Collimator Distance Y"
(0019,0050) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Bucky Height"
(0019,0060) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Bucky Angle"
(0019,0068) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="C-Arm Angle"
(0019,0069) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Collimator Angle"
(0019,0070) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Filter Number"
(0019,0074) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Filter Material 1"
(0019,0075) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Filter Material 2"
(0019,0078) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Filter Thickness 1"
(0019,0079) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Filter Thickness 2"
(0019,0080) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Bucky Format"
(0019,0081) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Object Position"
(0019,0090) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Desk Command"
(0019,0091) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Central Beam X"
(0019,0092) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Central Beam Y"
(0019,0093) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Tube Turn Angle"
(0019,0094) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Stand Drive Level"
(0019,00a0) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Extended Exposure Time"
(0019,00a1) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Actual Exposure Time"
(0019,00a8) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Extended X-ray Tube Current"
(0019,00b0) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Dose Indicator"
(0019,00b1) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Shift Reference Value"
(0019,00f0) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="?"

(0021,0000) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Noise Reduction"
(0021,0001) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Contrast Amplification"
(0021,0002) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Edge Contrast Boosting"
(0021,0003) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Latitude Reduction"
(0021,0010) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Find Range Algorithm"
(0021,0011) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Threshold C-Algorithm"
(0021,0020) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Sensometric Curve"
(0021,0030) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Lower Window Offset"
(0021,0031) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Upper Window Offset"
(0021,0040) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Minimal Printable Density"
(0021,0041) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Maximal Printable Density"
(0021,0050) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Minimal Window Latitude"
(0021,0051) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Maximal Window Latitude"
(0021,0052) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Relative Window Alignment"
(0021,0060) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Decomposition Layer"
(0021,0090) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Brightness"
(0021,0091) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Contrast"
(0021,0092) VERS="SWS"     VR="DS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Shape Factor"

(0023,0000) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Image Laterality"
(0023,0001) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Letter Position"
(0023,0002) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Burned In Annotation"
(0023,0003) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="?"		Name="?"
(0023,00f0) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Image SOP Class"

(0025,0000) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Original Image"
(0025,0001) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Not Processed Image"
(0025,0002) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Cut Out Image"
(0025,0003) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Duplicated Image"
(0025,0004) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Stored Image"
(0025,0005) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Retrieved Image"
(0025,0006) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="New Image"
(0025,0007) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Media Stored Image"
(0025,0008) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Image State"
(0025,0009) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Image Stitched Manually"
(0025,000a) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Image Stitched Automatically"
(0025,0020) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Source Image File"
(0025,0021) VERS="SWS"     VR="LO"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Source UID"

(0027,0000) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Number of Series" 
(0027,0001) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Number of Studies" 
(0027,0010) VERS="SWS"     VR="DT"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Oldest Series" 
(0027,0011) VERS="SWS"     VR="DT"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Newest Series" 
(0027,0012) VERS="SWS"     VR="DT"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Oldest Study" 
(0027,0013) VERS="SWS"     VR="DT"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Newest Study" 

(0029,0000) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Key Note Instance UID" 
(0029,0001) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Storage State" 
(0029,0002) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Referenced Image SOP Class" 
(0029,0003) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Referenced Image Instance UID" 
(0029,0004) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Related Presentation State Number" 
(0029,0005) VERS="SWS"     VR="IS"   VM="1"	Owner="SVISION"	Keyword="?"		Name="Related Presentation State UID" 

(5653,0010) VERS="VIT"     VR="OB"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="SavedWorkflow"				Name="Saved Workflow"
(5653,0011) VERS="VIT"     VR="LO"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="SavedWorkflowFileName"		Name="Saved Workflow File Name"
(5653,0012) VERS="VIT"     VR="OB"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="SavedWorkflowFileData"		Name="Saved Workflow File Data"
(5653,0013) VERS="VIT"     VR="SL"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="SavedWorkflowFileLength"	Name="Saved Workflow File Length"
(5653,0014) VERS="VIT"     VR="SQ"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="SavedWorkflowFileSequence"	Name="Saved Workflow File Sequence"
(5653,0015) VERS="VIT"     VR="SQ"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="ImageSequence"				Name="Image Sequence"
(5653,0016) VERS="VIT"     VR="SL"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="VolumeInterpolatedSlices"	Name="Volume Interpolated Slices"
(5653,0017) VERS="VIT"     VR="UI"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="VolumeSOPInstanceUID"		Name="Volume SOP Instance UID"
(5653,0018) VERS="VIT"     VR="SH"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="SavedWorkflowMark"			Name="Saved Workflow Mark"
(5653,0019) VERS="VIT"     VR="UI"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="?"							Name="?"
(5653,0022) VERS="VIT"     VR="UI"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="?"							Name="?"
(5653,0023) VERS="VIT"     VR="LO"   VM="1"	Owner="Vital Images SW 3.4" 	Keyword="?"							Name="?"

(0781,0001) VERS="ALICE"   VR="US"   VM="1"	Owner="PI Private Block (0781:3000 - 0781:30FF)" 	Keyword="?"		Name="?"
(0781,0002) VERS="ALICE"   VR="US"   VM="1"	Owner="PI Private Block (0781:3000 - 0781:30FF)" 	Keyword="?"		Name="?"
(0781,0005) VERS="ALICE"   VR="FL"   VM="1"	Owner="PI Private Block (0781:3000 - 0781:30FF)" 	Keyword="?"		Name="?"
(0781,0009) VERS="ALICE"   VR="FL"   VM="4"	Owner="PI Private Block (0781:3000 - 0781:30FF)" 	Keyword="?"		Name="?"

(0203,0000) VERS="RVN"     VR="LO"   VM="1"	Owner="Riverain Medical" 	Keyword="?"		Name="?"
(0203,0001) VERS="RVN"     VR="LO"   VM="1"	Owner="Riverain Medical" 	Keyword="?"		Name="?"
(0203,0002) VERS="RVN"     VR="LO"   VM="1"	Owner="Riverain Medical" 	Keyword="?"		Name="?"
(0203,0003) VERS="RVN"     VR="LO"   VM="1"	Owner="Riverain Medical" 	Keyword="?"		Name="?"
(0203,0010) VERS="RVN"     VR="LO"   VM="1"	Owner="Riverain Medical" 	Keyword="?"		Name="?"
(0203,00f0) VERS="RVN"     VR="UI"   VM="1"	Owner="Riverain Medical" 	Keyword="?"		Name="?"
(0203,00f1) VERS="RVN"     VR="UI"   VM="1"	Owner="Riverain Medical" 	Keyword="?"		Name="?"

(0029,0010) VERS="INT"     VR="CS"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0011) VERS="INT"     VR="US"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0012) VERS="INT"     VR="US"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0013) VERS="INT"     VR="US"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0015) VERS="INT"     VR="DS"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0016) VERS="INT"     VR="US"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0017) VERS="INT"     VR="US"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0020) VERS="INT"     VR="LO"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="MD5Sum"		Name="MD5Sum"
(0029,0021) VERS="INT"     VR="US"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(0029,0022) VERS="INT"     VR="US"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,0001) VERS="INT"     VR="LO"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,0003) VERS="INT"     VR="AE"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,0004) VERS="INT"     VR="LO"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,0005) VERS="INT"     VR="AE"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,0007) VERS="INT"     VR="LO"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,0009) VERS="INT"     VR="LO"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,000A) VERS="INT"     VR="DA"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F01,000B) VERS="INT"     VR="TM"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F03,0001) VERS="INT"     VR="SQ"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F03,0002) VERS="INT"     VR="DT"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F03,0003) VERS="INT"     VR="LO"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"
(3F03,0004) VERS="INT"     VR="LO"   VM="1"	Owner="INTELERAD MEDICAL SYSTEMS" 	Keyword="?"		Name="?"

