DROP TABLE IF EXISTS public.transfer_recordset CASCADE;
DROP TABLE IF EXISTS public.transfer_idc CASCADE;
DROP TABLE IF EXISTS public.transfer_gc CASCADE;
DROP TABLE IF EXISTS public.transfer_aspera CASCADE;
DROP TABLE IF EXISTS public.transfer_wp CASCADE;
DROP TABLE IF EXISTS public.recordset_draft_file CASCADE;
DROP TABLE IF EXISTS public.recordset_draft CASCADE;
DROP TABLE IF EXISTS public.dataset_release_recordset CASCADE;
DROP TABLE IF EXISTS public.recordset_release_file CASCADE;
DROP TABLE IF EXISTS public.recordset_release CASCADE;
DROP TABLE IF EXISTS public.recordset_destination CASCADE;
DROP TABLE IF EXISTS public.recordset CASCADE;
DROP TABLE IF EXISTS public.dataset_release_transfer CASCADE;
DROP TABLE IF EXISTS public.wp_object_map CASCADE;
DROP TABLE IF EXISTS public.transfer_destination CASCADE;
DROP TABLE IF EXISTS public.recordset_license CASCADE;
DROP TABLE IF EXISTS public.dataset_release CASCADE;
DROP TABLE IF EXISTS public.dataset_relation CASCADE;
DROP TABLE IF EXISTS public.dataset CASCADE;

-- For pre-name change tables
--DROP TABLE IF EXISTS "public".collection_release_dataset;
--DROP TABLE IF EXISTS "public".transfer_wp;
--DROP TABLE IF EXISTS "public".transfer_idc;
--DROP TABLE IF EXISTS "public".transfer_gc;
--DROP TABLE IF EXISTS "public".transfer_dataset;
--DROP TABLE IF EXISTS "public".transfer_aspera;
--DROP TABLE IF EXISTS "public".dataset_release_file;
--DROP TABLE IF EXISTS "public".dataset_release_draft_file;
--DROP TABLE IF EXISTS "public".dataset_release_draft;
--DROP TABLE IF EXISTS "public".dataset_release;
--DROP TABLE IF EXISTS "public".dataset_destination;
--DROP TABLE IF EXISTS "public".dataset;
--DROP TABLE IF EXISTS "public".collection_release_transfer;
--DROP TABLE IF EXISTS "public".wp_object_map;
--DROP TABLE IF EXISTS "public".transfer_destination;
--DROP TABLE IF EXISTS "public".dataset_license;
--DROP TABLE IF EXISTS "public".collection_release;
--DROP TABLE IF EXISTS "public".collection_related;
--DROP TABLE IF EXISTS "public".collection;