#!/bin/sh
##  $Source: /home/bbennett/pass/archive/PosdaAppMacConfig/SetEnv,v $
##  $Date: 2015/09/01 15:28:15 $
##  $Revision: 1.1 $
## 
if [ $# -ne 1 ]; then
  echo "$0: Usage: <Application Stage Name>"
  exit -1;
fi

export APP_CONTROLLER_ROOT=$1
if [ ${APP_CONTROLLER_ROOT:0:1} = "/" ]; then
  echo "$0: Usage: <Application Stage Name>"
  exit -1;
fi
export APP_CONTROLLER_ROOT=~/$1
export APP_CONTROLLER_STAGE=`basename $APP_CONTROLLER_ROOT`
cd $APP_CONTROLLER_ROOT
export PS1="[\u@\h: $APP_CONTROLLER_STAGE]$ "

if [ ! -d "$APP_CONTROLLER_ROOT" ]; then
  echo "$0: root dir does not exist: $APP_CONTROLLER_ROOT."
  exit -1;
fi
if [ -z $PRE_PACKAGE_PATH ]; then
  export PRE_PACKAGE_PATH=/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/opt/local/bin
fi
export PERL5LIB=$PRE_PACKAGE_PERL5LIB
export PATH=$APP_CONTROLLER_ROOT/bin:$PRE_PACKAGE_PATH
export POSDA_HOME=$APP_CONTROLLER_ROOT/Posda
export FILEDISTAPP_HOME=$APP_CONTROLLER_ROOT/FileDist
export POSDA_CURATION_HOME=$APP_CONTROLLER_ROOT/PosdaCuration
export TCIA_CURATION_HOME=$APP_CONTROLLER_ROOT/TciaCuration
. $TCIA_CURATION_HOME/env/Setup $TCIA_CURATION_HOME
. $POSDA_CURATION_HOME/env/Setup $POSDA_CURATION_HOME
. $FILEDISTAPP_HOME/env/Setup $FILEDISTAPP_HOME
. $POSDA_HOME/env/Setup $POSDA_HOME

export POSDA_DEBUG=0
export POSDA_TEST_COMMANDS=$POSDA_HOME/test/Dispatch
export POSDA_TEST_SCRIPTS=$POSDA_HOME/test/Scripts
export POSDA_TPL=$POSDA_HOME/tpl
export POSDA_TEST_BIN=$POSDA_HOME/bin/test
