#!/usr/bin/env bash

export APP_CONTROLLER_ROOT="$(pwd)"
export APP_CONTROLLER_STAGE=`basename $APP_CONTROLLER_ROOT`

export PS1="Posda (\u::$APP_CONTROLLER_STAGE)> "

export PATH=$APP_CONTROLLER_ROOT/bin:$PATH
export POSDA_HOME=$APP_CONTROLLER_ROOT/Posda

# Automatically setup all installed apps
for i in **/env/Setup; do
  NAME=$(dirname $(dirname $i))  # ugly way to get the first dirname
  source $i $APP_CONTROLLER_ROOT/$NAME
done

###############################################################################
# Actual configuration variables
###############################################################################

export POSDA_DEBUG=0
export POSDA_TEST_COMMANDS=$POSDA_HOME/test/Dispatch
export POSDA_TEST_SCRIPTS=$POSDA_HOME/test/Scripts
export POSDA_TPL=$POSDA_HOME/tpl
export POSDA_TEST_BIN=$POSDA_HOME/bin/test

export POSDA_ROOT=$APP_CONTROLLER_ROOT
export POSDA_CACHE_ROOT=/cache/posda
export POSDA_PORT=64610

