#$Source: /home/bbennett/pass/archive/Posda/tpl/elmdict/agfa.tpl,v $
#$Date: 2010/04/30 18:53:53 $
#$Revision: 1.2 $
#
(0009,0010) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0011) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0013) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0014) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0015) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"

(0019,0010) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="ImageProcessingParameters"	Name="Image Processing Parameters"
(0019,0011) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="IdentificationData"		Name="Identification Data"
(0019,0013) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="SensitometryName"		Name="Sensitometry Name"
(0019,0014) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA"		Keyword="WindowLevelList"		Name="Window Level List"
(0019,0015) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="DoseMonitoring"		Name="Dose Monitoring"
(0019,0016) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="OtherInfo"			Name="Other Info"
(0019,001a) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0019,001b) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0019,0060) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="TotalNumberSeries"			Name="Total Number Series"
(0019,0061) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA"		Keyword="SessionNumber"				Name="Session Number"
(0019,0062) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA"		Keyword="IDStationName"				Name="ID Station Name"
(0019,0065) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="?"							Name="?"
(0019,0070) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="TotalNumberImages"			Name="Total Number Images"
(0019,0082) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="?"							Name="?"
(0019,0093) VERS="AGFA"	VR="CS"   VM="1"	Owner="AGFA"		Keyword="?"							Name="?"

(0019,0030) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="DataStreamFromCassette"	Name="Data stream from cassette"
(0019,0030) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SetOfDestinationTypes"		Name="Set of destination types"
(0019,0040) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SetOfDestinationIds"		Name="Set of destination Ids"
(0019,0050) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SetOfProcessingCodes"		Name="Set of processing codes"
(0019,0060) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="NumberOfSeriesInStudy"		Name="Number of series in study"
(0019,0061) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SessionNumber"			Name="Session Number"
(0019,0062) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="IDStationName"			Name="ID station name"
(0019,0070) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="NumberOfImagesInSeries"	Name="Number of images in series"
(0019,0071) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="BreakCondition"		Name="Break condition"
(0019,0072) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="WaitOrHoldFlag"		Name="Wait (or Hold) flag"
(0019,0073) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="ScanResFlag"			Name="ScanRes flag"
(0019,0074) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="OperationCode"			Name="Operation code"
(0019,0095) VERS="AGFA"	VR="CS"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="ImageQuality"			Name="Image quality"

(0019,0009) VERS="AGFA"	VR="SQ"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00f0) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField1"	Name="User Defined field 1"
(0019,00f1) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField2"	Name="User Defined field 2"
(0019,00f2) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField3"	Name="User Defined field 3"
(0019,00f3) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField4"	Name="User Defined field 4"
(0019,00f4) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField5"	Name="User Defined field 5"
(0019,00f5) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="CassetteOrientation"	Name="Cassette Orientation"
(0019,00f6) VERS="AGFA"	VR="DS"   VM="1"	Owner="Agfa ADC NX"	Keyword="PlateSensitivity"	Name="Plate Sensitivity"
(0019,00f7) VERS="AGFA"	VR="DS"   VM="1"	Owner="Agfa ADC NX"	Keyword="PlateErasability"	Name="Plate Erasability"
(0019,00f8) VERS="AGFA"	VR="IS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fa) VERS="AGFA"	VR="IS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fc) VERS="AGFA"	VR="IS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fd) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fe) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"

(0031,0000) VERS="MIT"  VR="CS"   VM="1"	Owner="AGFA PACS Archive Mirroring 1.0"	Keyword="?"		Name="?"
(0031,0001) VERS="MIT"  VR="UL"   VM="1"	Owner="AGFA PACS Archive Mirroring 1.0"	Keyword="?"		Name="?"

(0029,0000) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"
(0029,0001) VERS="MIT"  VR="UN"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"
(0029,0002) VERS="MIT"  VR="UN"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"
(0029,0003) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"

(0029,0000) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT DOCUMENT 1.0"	Keyword="?"		Name="?"

(0029,0000) VERS="MIT"  VR="LO"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="?"		Name="?"
(0029,0001) VERS="MIT"  VR="LO"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="?"		Name="?"

(0029,0011) VERS="AGFA"    VR="CS"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,0012) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,0013) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,0014) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,001f) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"

(0033,0002) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0004) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0006) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0008) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000a) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000c) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000e) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0013) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0014) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0015) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0016) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0019) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"

(0033,0002) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0004) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0006) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0008) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000a) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"

(0031,0020) VERS="MIT"  VR="IS"   VM="1"	Owner="MITRA LINKED ATTRIBUTES 1.0"	Keyword="?"		Name="?"

(0071,0018) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0019) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,001a) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,001c) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,001e) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0020) VERS="AGFA"	VR="FL"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0021) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0022) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0023) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0024) VERS="AGFA"	VR="FD"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"

(0073,0023) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0073,0024) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0073,0028) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0073,0080) VERS="AGFA"	VR="FL"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"

(0075,0010) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"

(0087,0001) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0002) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
