#$Source: /home/bbennett/pass/archive/Posda/tpl/elmdict/papyrus.tpl,v $
#$Date: 2010/04/30 18:53:53 $
#$Revision: 1.2 $
#
(0009,0000) VERS="PAP"  VR="LT"   VM="1"	Owner="PAPYRUS"	Keyword="OriginalFileName"			Name="Original File Name"
(0009,0010) VERS="PAP"  VR="LT"   VM="1"	Owner="PAPYRUS"			Keyword="OriginalFileLocation"		Name="Original File Location"
(0009,0018) VERS="PAP"  VR="LT"   VM="1"	Owner="PAPYRUS"			Keyword="DataSetIdentifier"		Name="Data Set Identifier"
(0041,0000) VERS="PA3"	VR="LT"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="PapyrusComments"			Name="Papyrus Comments"
(0041,0000) VERS="PAP"	VR="LT"   VM="1-n"	Owner="PAPYRUS"	Keyword="PapyrusComments"			Name="Papyrus Comments"
(0041,0010) VERS="PA3"	VR="SQ"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="PointerSequence"			Name="Pointer Sequence"
(0041,0010) VERS="PAP"	VR="US"   VM="1"	Owner="PAPYRUS"	Keyword="FolderType"			Name="Folder Type"
(0041,0011) VERS="PA3"	VR="UL"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ImagePointer"			Name="Image Pointer"
(0041,0011) VERS="PAP"	VR="LT"   VM="1"	Owner="PAPYRUS"	Keyword="PatientFolderDataSetID"			Name="Patient Folder Data Set ID"
(0041,0012) VERS="PA3"	VR="UL"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="PixelOffset"			Name="Pixel Offset"
(0041,0013) VERS="PA3"	VR="SQ"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ImageIdentifierSequence"			Name="Image Identifier Sequence"
(0041,0014) VERS="PA3"	VR="SQ"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ExternalFileReferenceSequence"			Name="External File Reference Sequence"
(0041,0015) VERS="PA3"	VR="US"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="NumberOfImages"			Name="Number of Images"
(0041,0020) VERS="PAP"	VR="LT"   VM="1"	Owner="PAPYRUS"	Keyword="FolderName"			Name="Folder Name"
(0041,0021) VERS="PA3"	VR="UI"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ReferencedSOPClassUID"			Name="Referenced SOP Class UID"
(0041,0022) VERS="PA3"	VR="UI"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ReferencedSOPInstanceUID"			Name="Referenced SOP Instance UID"
(0041,0030) VERS="PAP"	VR="DA"   VM="1"	Owner="PAPYRUS"	Keyword="CreationDate"			Name="Creation Date"
(0041,0031) VERS="PA3"  VR="LT"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ReferencedFileName"			Name="Referenced File Name"
(0041,0032) VERS="PA3"  VR="LT"   VM="1-n"	Owner="PAPYRUS 3.0"	Keyword="ReferencedFilePath"			Name="Referenced File Path"
(0041,0032) VERS="PAP"	VR="TM"   VM="1"	Owner="PAPYRUS"	Keyword="CreationTime"			Name="Creation Time"
(0041,0034) VERS="PAP"	VR="DA"   VM="1"	Owner="PAPYRUS"	Keyword="ModifiedDate"			Name="Modified Date"
(0041,0036) VERS="PAP"	VR="TM"   VM="1"	Owner="PAPYRUS"	Keyword="ModifiedTime"			Name="Modified Time"
(0041,0040) VERS="PAP"	VR="LT"   VM="1-n"	Owner="PAPYRUS"	Keyword="OwnerName"			Name="Owner Name"
(0041,0041) VERS="PA3"	VR="UI"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ReferencedImageSOPClassUID"			Name="Referenced Image SOP Class UID"
(0041,0042) VERS="PA3"	VR="UI"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ReferencedImageSOPInstanceUID"			Name="Referenced Image SOP Instance UID"
(0041,0050) VERS="PA3"	VR="SQ"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ImageSequence"			Name="Image Sequence"
(0041,0050) VERS="PAP"	VR="LT"   VM="1"	Owner="PAPYRUS"	Keyword="FolderStatus"			Name="Folder Status"
(0041,0060) VERS="PAP"	VR="UL"   VM="1"	Owner="PAPYRUS"	Keyword="NumberOfImages"			Name="Number of Images"
(0041,0062) VERS="PAP"	VR="UL"   VM="1"	Owner="PAPYRUS"	Keyword="NumberOfOther"			Name="Number of Other"
(0041,00a0) VERS="PAP"	VR="LT"   VM="1-n"	Owner="PAPYRUS"	Keyword="ExternalFolderElementDSID"			Name="External Folder Element DSID"
(0041,00a1) VERS="PAP"	VR="US"   VM="1-n"	Owner="PAPYRUS"	Keyword="ExternalFolderElementDataSetType"			Name="External Folder Element Data Set Type"
(0041,00a2) VERS="PAP"	VR="LT"   VM="1-n"	Owner="PAPYRUS"	Keyword="ExternalFolderElementFileLocation"			Name="External Folder Element File Location"
(0041,00a3) VERS="PAP"	VR="UL"   VM="1-n"	Owner="PAPYRUS"	Keyword="ExternalFolderElementLength"			Name="External Folder Element Length"
(0041,00b0) VERS="PAP"	VR="LT"   VM="1-n"	Owner="PAPYRUS"	Keyword="InternalFolderElementDSID"			Name="Internal Folder Element DSID"
(0041,00b1) VERS="PAP"	VR="US"   VM="1-n"	Owner="PAPYRUS"	Keyword="InternalFolderElementDataSetType"			Name="Internal Folder Element Data Set Type"
(0041,00b2) VERS="PAP"	VR="UL"   VM="1-n"	Owner="PAPYRUS"	Keyword="InternalOffsetToDataSet"			Name="Internal Offset To Data Set"
(0041,00b3) VERS="PAP"	VR="UL"   VM="1-n"	Owner="PAPYRUS"	Keyword="InternalOffsetToImage"			Name="Internal Offset To Image"
(60xx,0000) VERS="PA3"	VR="IS"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayID"		Name="Overlay ID"
(60xx,0001) VERS="PA3"	VR="LT"   VM="1-n"	Owner="PAPYRUS 3.0"	Keyword="LinkedOverlays"	Name="Linked Overlays"
(60xx,0010) VERS="PA3"	VR="US"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayRows"		Name="Overlay Rows"
(60xx,0011) VERS="PA3"	VR="US"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayColumns"	Name="Overlay Columns"
(60xx,0040) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayType"		Name="Overlay Type"
(60xx,0050) VERS="PA3"	VR="US"   VM="1-n	Owner="PAPYRUS 3.0"	Keyword="OverlayOrigin"		Name="Overlay Origin"
(60xx,0060) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="Editable"		Name="Editable"
(60xx,0070) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayFont"		Name="Overlay Font"
(60xx,0072) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayStyle"		Name="Overlay Style"
(60xx,0074) VERS="PA3"	VR="US"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayFontSize"	Name="Overlay Font Size"
(60xx,0076) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayColor"		Name="Overlay Color"
(60xx,0078) VERS="PA3"	VR="US"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ShadowSize"		Name="Shadow Size"
(60xx,0080) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="FillPattern"		Name="Fill Pattern"
(60xx,0082) VERS="PA3"	VR="US"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="OverlayPenSize"	Name="Overlay Pen Size"
(60xx,00a0) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="Label"			Name="Label"
(60xx,00a2) VERS="PA3"	VR="LT"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="PostItText"		Name="Post It Text"
(60xx,00a4) VERS="PA3"	VR="US"   VM="2"	Owner="PAPYRUS 3.0"	Keyword="AnchorPoint"		Name="Anchor Point"
(60xx,00b0) VERS="PA3"	VR="LO"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="ROIType"		Name="ROI Type"
(60xx,00b2) VERS="PA3"	VR="LT"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="AttachedAnnotation"	Name="Attached Annotation"
(60xx,00ba) VERS="PA3"	VR="US"   VM="1-n"	Owner="PAPYRUS 3.0"	Keyword="ContourPoints"		Name="Contour Points"
(60xx,00bc) VERS="PA3"	VR="US"   VM="1-n"	Owner="PAPYRUS 3.0"	Keyword="MaskData"		Name="Mask Data"
(60xx,00c0) VERS="PA3"  VR="SQ"   VM="1"	Owner="PAPYRUS 3.0"	Keyword="UINOverlaySequence"	Name="UIN Overlay Sequence"
