#
(0009,0000) VERS="TSH"  VR="LO"   VM="1"	Owner="TOSHIBA_MEC_OT3"	Keyword="HISRISStudyID"			Name="HIS/RIS Study ID"
(0009,0001) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0009,0002) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0009,0003) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0009,0004) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0011,0001) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_1.0"		Keyword="?"				Name="?"
(0011,0002) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"		Keyword="?"				Name="?"
(0019,0001) VERS="TSH"	VR="IS"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0019,0001) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0019,0002) VERS="TSH"	VR="IS"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0019,0002) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0019,0003) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0019,0004) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0019,0005) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0019,0006) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0019,0007) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0019,0008) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="OrientationHeadFeet"			Name="Orientation Head Feet"
(0019,0009) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="ViewDirection"					Name="View Direction"
(0019,000a) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="OrientationSupineProne"		Name="Orientation Supine Prone"
(0019,000b) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="Location"						Name="Location"
(0019,000c) VERS="TSH"	VR="CS"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="ScanViewDirection"				Name="Scan View Direction"
(0019,000d) VERS="TSH"	VR="TM"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="Time"							Name="Time"
(0019,000e) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"			Name="?"
(0021,0001) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0021,0002) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0021,0003) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"	Keyword="?"			Name="?"
(0029,0008) VERS="TSH"	VR="CS"   VM="1"	Owner="TOSHIBA MDW NON-IMAGE"	Keyword="NonImageHeaderType"		Name="Non-Image Header Type"
(0029,0009) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA MDW NON-IMAGE"	Keyword="NonImageHeaderVersion"		Name="Non-Image Header Version"
(0029,0020) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA MDW NON-IMAGE"	Keyword="?"							Name="?"
(0029,0008) VERS="TSH"	VR="CS"   VM="1"	Owner="TOSHIBA MDW HEADER"	Keyword="ImageHeaderType"				Name="Image Header Type"
(0029,0009) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA MDW HEADER"	Keyword="ImageHeaderVersion"			Name="Image Header Version"
(0029,0010) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA MDW HEADER"	Keyword="ImageHeaderInfo"				Name="Image Header Info"
(0029,0018) VERS="TSH"	VR="CS"   VM="1"	Owner="TOSHIBA MDW HEADER"	Keyword="SeriesHeaderType"				Name="Series Header Type"
(0029,0019) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA MDW HEADER"	Keyword="SeriesHeaderVersion"			Name="Series Header Version"
(0029,0020) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA MDW HEADER"	Keyword="SeriesHeaderInfo"				Name="Series Header Info"
(0029,0008) VERS="TSH"	VR="CS"   VM="1"	Owner="TOSHIBA COMAPL HEADER"	Keyword="COMAPLHeaderType"			Name="COMAPL Header Type"
(0029,0009) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA COMAPL HEADER"	Keyword="COMAPLHeaderVersion"		Name="COMAPL Header Version"
(0029,0010) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA COMAPL HEADER"	Keyword="COMAPLHeaderInfo"			Name="COMAPL Header Info"
(0029,0020) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA COMAPL HEADER"	Keyword="COMAPLHistoryInformation"	Name="COMAPL History Information"
(0029,0031) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA COMAPL HEADER"	Keyword="?"	Name="?"
(0029,0034) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA COMAPL HEADER"	Keyword="?"	Name="?"
(0029,0008) VERS="TSH"	VR="CS"   VM="1"	Owner="TOSHIBA COMAPL OOG"	Keyword="COMAPLOOGType"					Name="COMAPL OOG Type"
(0029,0009) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA COMAPL OOG"	Keyword="COMAPLOOGVersion"				Name="COMAPL OOG Version"
(0029,0010) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA COMAPL OOG"	Keyword="COMAPLOOGInfo"					Name="COMAPL OOG Info"
(0029,0001) VERS="TSH"	VR="SQ"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="?"							Name="?"
(0029,0031) VERS="TSH"	VR="LO"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="PMTFInformation1"			Name="PMTF Information 1"
(0029,0032) VERS="TSH"	VR="UL"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="PMTFInformation2"			Name="PMTF Information 2"
(0029,0033) VERS="TSH"	VR="UL"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="PMTFInformation3"			Name="PMTF Information 3"
(0029,0034) VERS="TSH"	VR="CS"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="PMTFInformation4"			Name="PMTF Information 4"
(0029,0089) VERS="TSH"	VR="LO"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="?"							Name="?"
(0029,0090) VERS="TSH"	VR="OB"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="?"							Name="?"
(7005,0000) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="BlackBox1"										Name="Black Box 1"
(7005,0003) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="CardiacRRMeanTime"								Name="Cardiac R-R Mean Time"
(7005,0004) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="CardiacReconstructionGettingPhaseInPercent"	Name="Cardiac Reconstruction Getting Phase in Percent"
(7005,0005) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="CardiacReconstructionGettingPhaseInMS"			Name="Cardiac Reconstruction Getting Phase in ms"
(7005,0006) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="CardiacReconstructionMode"						Name="Cardiac Reconstruction Mode"
(7005,0007) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="ReconstructionCenter"							Name="Reconstruction Center"
(7005,0008) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="DetectorSliceThickness"						Name="Detector Slice Thickness in mm"
(7005,0009) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="NumberOfDetectorRowsToReconstruct"				Name="Number of Detector rows to Reconstruct"
(7005,000a) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="TableSpeed"									Name="Table Speed in mm/rot"
(7005,000b) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="Filter"										Name="Filter"
(7005,000c) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="ReconstructionCorrectionType"					Name="Reconstruction Correction Type"
(7005,000d) VERS="TSH"	VR="CS"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="Organ"											Name="Organ"
(7005,000e) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="FileTypeRemarks"								Name="File Type Remarks"
(7005,000f) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="Direction"										Name="Direction (head or feet first)"
(7005,0010) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="BlackBox2"										Name="Black Box 2"
(7005,0011) VERS="TSH"	VR="LT"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="SeriesComment"									Name="Series Comment"
(7005,0012) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="Position"										Name="Position (supine or prone)"
(7005,0013) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="ExpertPlanNumber"								Name="Expert Plan Number"
(7005,0014) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="ReconstructionROINumber"						Name="Reconstruction ROI Number"
(7005,0015) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="SpecialHelicalAcquisitionNumber"				Name="Special Helical Acquisition Number"
(7005,0016) VERS="TSH"	VR="UI"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="VolumeUID"										Name="Volume UID"
(7005,0017) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="TotalFrameCountInTheVolume"					Name="Total Frame Count in the Volume"
(7005,0018) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="FrameNumber"									Name="Frame Number"
(7005,0019) VERS="TSH"	VR="UL"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="FrameSortKey"									Name="Frame Sort Key"
(7005,001a) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="FrameSortOrder"								Name="Frame Sort Order"
(7005,001b) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="ConvolutionKernelForSeriesRecord"				Name="Convolution Kernel for Series Record"
(7005,001c) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="ContrastBolusAgentForSeriesRecord"				Name="Contrast/Bolus Agent for Series Record"
(7005,001d) VERS="TSH"	VR="UL"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="ReconstructionNumber"							Name="Reconstruction Number"
(7005,001e) VERS="TSH"	VR="UL"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="RawDataNumber"									Name="Raw Data Number"
(7005,001f) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="VolumeNumber"									Name="Volume Number"
(7005,0020) VERS="TSH"	VR="UL"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="LocalSeriesNumber"								Name="Local Series Number"
(7005,0021) VERS="TSH"	VR="UN"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="?"		Name="?"
(7005,0022) VERS="TSH"	VR="UN"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="?"		Name="?"
(7005,0023) VERS="TSH"	VR="UN"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="?"		Name="?"
(7005,0030) VERS="TSH"	VR="UN"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="?"		Name="?"
(7005,0040) VERS="TSH"	VR="UN"   VM="1"	Owner="TOSHIBA_MEC_CT3"	Keyword="?"		Name="?"
(700d,0000) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="ScaleFactor"			Name="Scale Factor"
(700d,0001) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="AcquisitionOrder"		Name="Acquisition Order"
(700d,0002) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="OrientationVector"		Name="Orientation Vector"
(700d,0003) VERS="TSH"	VR="SS"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="FlipFlag"				Name="Flip Flag"
(700d,0004) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="RotateInformation"		Name="Rotate Information"
(700d,0005) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="FOV"					Name="FOV"
(700d,0006) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="ImageMatrix"			Name="Image Matrix"
(700d,0007) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="ImageInformation"		Name="Image Information"
(700d,0008) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="OriginalData"			Name="Original Data"
(700d,0009) VERS="TSH"	VR="SS"   VM="1"	Owner="TOSHIBA_MEC_MR3"	Keyword="OriginalDataFlag"		Name="Original Data Flag"
(7015,0000) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA ENCRYPTED SR DATA"	Keyword="?"			Name="?"
(7015,0010) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_SR"	Keyword="?"			Name="?"
(7015,0060) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_SR"	Keyword="?"							Name="?"
(7015,0073) VERS="TSH"	VR="SQ"   VM="1"	Owner="PMTF INFORMATION DATA"	Keyword="?"							Name="?"
(7079,0021) VERS="TSH"	VR="SH"   VM="5"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0022) VERS="TSH"	VR="IS"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0023) VERS="TSH"	VR="IS"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0024) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0025) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0026) VERS="TSH"	VR="DS"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0027) VERS="TSH"	VR="US"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0028) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,002a) VERS="TSH"	VR="US"   VM="5"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,002c) VERS="TSH"	VR="SH"   VM="3"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,002d) VERS="TSH"	VR="SS"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,002e) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,002f) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0030) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0031) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0032) VERS="TSH"	VR="SH"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0033) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0034) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0035) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0036) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0037) VERS="TSH"	VR="US"   VM="4"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0038) VERS="TSH"	VR="SS"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0039) VERS="TSH"	VR="SS"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,003a) VERS="TSH"	VR="US"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,003b) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,003c) VERS="TSH"	VR="DS"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,003d) VERS="TSH"	VR="SS"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,003e) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,003f) VERS="TSH"	VR="US"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0040) VERS="TSH"	VR="SH"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0041) VERS="TSH"	VR="SS"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0042) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0043) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0044) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0045) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0046) VERS="TSH"	VR="SS"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0047) VERS="TSH"	VR="SS"   VM="18"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0048) VERS="TSH"	VR="US"   VM="12"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0049) VERS="TSH"	VR="US"   VM="3"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,004a) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,004b) VERS="TSH"	VR="LO"   VM="3"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,004c) VERS="TSH"	VR="OB"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,004d) VERS="TSH"	VR="SH"   VM="3"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,004e) VERS="TSH"	VR="SL"   VM="35"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,004f) VERS="TSH"	VR="SH"   VM="3"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0050) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0051) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0052) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0053) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0054) VERS="TSH"	VR="US"   VM="5"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0055) VERS="TSH"	VR="UL"   VM="47-47n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0056) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0057) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0058) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0059) VERS="TSH"	VR="US"   VM="2-2n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,005a) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,005b) VERS="TSH"	VR="US"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,005c) VERS="TSH"	VR="US"   VM="2-2n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,005d) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,005e) VERS="TSH"	VR="US"   VM="2"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,005f) VERS="TSH"	VR="SS"   VM="4-4n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0060) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0061) VERS="TSH"	VR="SS"   VM="30-30n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0062) VERS="TSH"	VR="US"   VM="4"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0063) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0064) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0065) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0066) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0067) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0068) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0069) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,006a) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,006b) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,006c) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,006d) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,006e) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,006f) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0070) VERS="TSH"	VR="DS"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0071) VERS="TSH"	VR="DS"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0072) VERS="TSH"	VR="DS"   VM="1-n"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0073) VERS="TSH"	VR="SL"   VM="4"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0074) VERS="TSH"	VR="SL"   VM="28"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0075) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?" 
(7079,0076) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?" 
(7079,0077) VERS="TSH"	VR="SL"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0078) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0079) VERS="TSH"	VR="US"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,007b) VERS="TSH"	VR="SH"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7079,0080) VERS="TSH"	VR="LO"   VM="1"	Owner="TOSHIBA_MEC_XA3"	Keyword="?"		Name="?"
(7ff1,0001) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"		Keyword="?"		Name="?"
(7ff1,0001) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0002) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"		Keyword="?"		Name="?"
(7ff1,0002) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0003) VERS="TSH"	VR="IS"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0003) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"		Keyword="?"		Name="?"
(7ff1,0004) VERS="TSH"	VR="IS"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0005) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0007) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0008) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0009) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,000a) VERS="TSH"  VR="LT"   VM="1"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,000b) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,000c) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,000d) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_CT_1.0"	Keyword="?"		Name="?"
(7ff1,0010) VERS="TSH"	VR="US"   VM="1-n"	Owner="TOSHIBA_MEC_1.0"		Keyword="?"		Name="?"
