#
StringValues="OverlaySubtypeUS" {
	ACTIVE 2D/BMODE IMAGE AREA = Identification of the active area of a 2D/B-mode image
}

StringValues="USPhotometricInterpretation" {
	MONOCHROME2,
	PALETTE COLOR,
	RGB,
	ARGB,
	YBR_FULL,
	YBR_FULL_422,
	YBR_PARTIAL_422,
	YBR_RCT,
	YBR_ICT
}

StringValues="USImageType3"	{
	ABDOMINAL,
	BREAST,
	CHEST,
	ENDOCAVITARY,
	ENDORECTAL,
	ENDOVAGINAL,
	EPICARDIAL,
	FETAL HEART,
	GYNECOLOGY,
	INTRACARDIAC,
	INTRAOPERATIVE,
	INTRAVASCULAR,
	MUSCULOSKELETAL,
	NEONATAL HEAD,
	OBSTETRICAL,
	OPHTHALMIC,
	PEDIATRIC,
	PELVIC,
	RETROPERITONEAL,
	SCROTAL,
	SMALL PARTS,
	TEE,
	THYROID,
	TRANSCRANIAL,
	TTE,
	USBIOPSY,
	VASCULAR
}

StringValues="USTransducerPosition" {
	ANTERIOR,
	AORTA,
	APICAL ,
	ARTERY,
	BASAL ESOPHAGUS,
	BYPASS GRAFT,
	CAUDAL,
	CRANIAL,
	DISTAL,
	ENDOVAGINAL,
	ENDORECTAL,
	EPICARDIAL,
	ESOPHAGUS,
	GASTRIC,
	INFERIOR,
	L ATRIUM,
	L CORONARY ART,
	L LIQ,
	L LOQ,
	L PARASTERN,
	L SUBCLAVIAN,
	L SUPRACLAVICULAR,
	L UIQ,
	L UOQ,
	L VENTRICLE LATER,
	LEFT,
	LEFT PARA,
	LOWER ESOPHAGUS,
	MEDIAL,
	MID ESOPHAGUS,
	MIDLINE,
	OCCIPITAL,
	POSTERIOR,
	PROXIMAL,
	PULMONARY ART,
	R ATRIUM,
	R CORONARY ART,
	R LIQ,
	R LOQ,
	R PARASTERN,
	R SUBCLAVIAN,
	RSUPRACLAVICULAR,
	R UIQ,
	R UOQ,
	R VENTRICLE,
	RIGHT,
	RIGHT PARA,
	SUBCLAVIAN,
	SUBCOSTAL,
	SUP STERN NOTCH,
	SUPERIOR ,
	SUPRACLAVICULAR,
	SURFACE,
	TRANSGASTRIC,
	TRANSORBITAL,
	TRANSTEMPORAL,
	UPPER ESOPHAGUS,
	VEIN
}

StringValues="USTransducerOrientation" {
	2 CHAMBER,
	4 CHAMBER,
	5 CHAMBER,
	AXIAL,
	CORONAL,
	L PARASAG,
	LONG AXIS,
	LONGITUDINAL,
	OBLIQUE,
	R PARASAG,
	SAGITTAL,
	SHORT AXIS,
	TRANSVERSE
}

StringValues="USAnatomicStructure" {
	4 CH HEART,
	3RD VENTRICLE,
	4TH VENTRICLE,
	AC,
	ADRENAL,
	AMNIOTIC FLUID,
	AORTA,
	APPENDIX,
	ASCENDING COLON,
	BASILAR ART,
	BILE DUCT,
	BLADDER,
	BPD,
	C SPINE,
	CELIAC ART,
	CENTRAL ZONE,
	CEREBELLUM,
	CEREB HEMISPHERE,
	CERVIX,
	COLON,
	CUL DE SAC,
	DESCENDING COLON,
	DUODENUM,
	ENDOMETRIUM,
	FETAL ARMS,
	FETAL DIGITS,
	FETAL HEART,
	FETAL LEGS,
	FETAL POLE,
	FEMUR LENGTH,
	FUNDUS,
	GALLBLADDER,
	GEST SAC,
	HC,
	HEPATIC ART,
	ILEUM,
	ISTHMUS,
	INF MES ART,
	INF VENA CAVA,
	L ACA,
	L AXILLARY A,
	L AXILLARY V,
	L BRACHIAL A,
	L BRACHIAL V,
	L BREAST,
	L BULB,
	L CCA,
	L CFA,
	L CFV,
	L CHOROID PLEXUS,
	L COM ILIAC ART,
	L COM ILIAC V,
	L ECA,
	L EPIDIDYMIS,
	L EXT ILIAC A,
	L EXT ILIAC V,
	L EXT JUG V,
	L EYE,
	L FEMUR,
	L GSV,
	L HEPATIC V,
	L HUMERUS,
	L ICA,
	L ILIAC A,
	L ILIAC V,
	L INT JUG V,
	L KIDNEY,
	L MCA,
	L OVARY,
	L PCA ,
	L POP A,
	L POP V,
	L PROF FEM A,
	L PROF FEM V,
	L RADIAL A,
	L RADIUS,
	L RENAL ART,
	L RENAL V,
	L SEM VESICLE,
	L SAPH V,
	L SFA,
	L SFV,
	L SPINE,
	L SUBCLAVIAN A,
	L SUBCLAVIAN V,
	L TESTIS,
	L THALAMUS,
	L TIB FIB,
	L ULNA,
	L ULNAR ART,
	L VENTRICLE,
	L VERT,
	LAT VENTRICLES,
	LIVER,
	L PORTAL V,
	MID HEPATIC V,
	MORRISONS POUCH,
	OFD,
	PANCREAS,
	PENILE VESSELS,
	PERIPHERAL ZONE,
	PLACENTA,
	PORTAL V,
	PROSTATE,
	R ACA,
	R AXILLARY A,
	R AXILLARY V,
	R BRACHIAL A,
	R BRACHIAL V,
	R BREAST,
	R BULB,
	R CCA,
	R CFA,
	R CFV,
	R CHOROID PLEXUS
	R COM ILIAC ART,
	R COM ILIAC V,
	R ECA,
	R EYE,
	R EPIDIDYMIS,
	R EXT ILIAC A,
	R EXT ILIAC V,
	R EXT JUV V,
	R FEMUR,
	R GSV,
	R HEPATIC V,
	R HUMERUS,
	R ICA,
	R ILIAC A,
	R ILIAC V,
	R INT JUG V,
	R KIDNEY,
	R MCA,
	R OVARY,
	R PCAR POP A,
	R POP V,
	R PROF FEM A,
	R PROF FEM V,
	R RADIAL A,
	R RADIUS,
	R RENAL ART,
	R RENAL V,
	R SAPH V,
	R SEM VESICLE,
	R SFA,
	R SFV,
	R SUBCLAVIAN A,
	R SUBCLAVIAN V,
	R TESTIS,
	R THALAMUS,
	R TIB FIB,
	R ULNA,
	R ULNAR ART,
	R VENTRICLE,
	R VERT,
	R PORTAL V,
	RECTUM,
	RETROPERITONEUM,
	SACRUM,
	SCROTUM,
	SIGMOID,
	SMA,
	SMALL INTESTINE,
	SMV,
	SPLEEN,
	SPLENIC ART,
	SPLENIC V,
	STOMACH,
	TESTICLE,
	T SPINE,
	THYROID,
	TRANSITION ZONE,
	TRANSVERSE COLON,
	SIGMOID,
	UMB CORD,
	UTERINE FUNDUS,
	UTERUS,
	VAGINA,
	YOLK SAC,
	ABD AO,
	AO ANNULUS,
	AO ARCH,
	AO LFLT TIPS,
	AO VALVE,
	ASCENDING AO,
	ASD,
	AZYGOS VEIN,
	CORONARY SINUS,
	DIAGONAL,
	DISTAL LAD,
	DISTAL LCX,
	DISTAL RCA,
	IAS,
	INNOMINATE A,
	INT ATRIAL SEPT,
	INT VENT SEPT,
	IVS,
	L ATRIAL APPEN,
	L ATRIUM,
	L FOOT,
	L GERMINAL MATRX,
	L HIP,
	L SHOULDER,
	L MAIN COR ART,
	L SAPH V,
	L SVC,
	LAD,
	LAD D1,
	LAD D2,
	LAD D3,
	LAD S1,
	LAD S2,
	LCX,
	LCXDM1,
	LCXDM2,
	LIMA,
	LLPV,
	LOWER DESC AO,
	LPA,
	LPV,
	LUPV,
	LV APEX,
	LV BASE,
	LV CAVITY,
	LV MID,
	LVOT,
	MAIN PA,
	MID LAD,
	MID LCX,
	MID RCA,
	MITRAL ANNULUS,
	MITRAL LFLT TIPS,
	MITRAL VALVE,
	OBTUSE MARGINAL,
	PERINEUM,
	PLV COR ART,
	POST DESC ART,
	POST LV BRANCH,
	PROX CIRC,
	PROX LAD,
	PROX LCX,
	PROX RCA,
	PULM ANNULUS,
	PULM VALVE,
	PULM VEIN,
	PV TIPS,
	R ATRIUM,
	R FOOT,
	R GERMINAL MATRX,
	R HIP,
	R PV,
	R SAPH V,
	R SHOULDER,
	RAA,
	RCA,
	RIMA,
	RLPV,
	RPA,
	RUPV,
	RV CAVITY,
	RVOT,
	SAPH V GRAFT LAD,
	SUP VENA CAVA,
	SVG D,
	SVG LAD,
	SVG LCX,
	SVG OM,
	SVG PDA,
	SVG PLV,
	SVG RCA,
	TRICUSPID ANN,
	TRICUSPID TIPS,
	TRICUSPID VALVE,
	UPPER DESC AO,
	VSD
}

StringValues="USTransducerType" {
	SECTOR_PHASED,
	SECTOR_MECH,
	SECTOR_ANNULAR,
	LINEAR,
	CURVED LINEAR,
	SINGLE CRYSTAL,
	SPLIT XTAL CWD,
	IV_PHASED,
	IV_ROT XTAL,
	IV_ROT MIRROR,
	ENDOCAV_PA,
	ENDOCAV_MECH,
	ENDOCAV_CLA,
	ENDOCAV_AA,
	ENDOCAV_LINEAR,
	VECTOR_PHASED
}

StringValues="USImageType4"	{
	0001 = 2D Imaging,
	0002 = M-Mode,
	0003 = 2D Imaging + M-Mode,
	0004 = CW Doppler,
	0005 = 2D Imaging + CW Doppler,
	0006 = M-Mode + CW Doppler,
	0007 = 2D Imaging + M-Mode + CW Doppler,
	0008 = PW Doppler,
	0009 = 2D Imaging + PW Doppler,
	000a = M-Mode + PW Doppler,
	000b = 2D Imaging + M-Mode + PW Doppler,
	000c = CW Doppler + PW Doppler,
	000d = 2D Imaging + CW Doppler + PW Doppler,
	000e = M-Mode + CW Doppler + PW Doppler,
	000f = 2D Imaging + M-Mode + CW Doppler + PW Doppler,
	0010 = Color Doppler,
	0011 = 2D Imaging + Color Doppler,
	0012 = M-Mode + Color Doppler,
	0013 = 2D Imaging + M-Mode + Color Doppler,
	0014 = CW Doppler + Color Doppler,
	0015 = 2D Imaging + CW Doppler + Color Doppler,
	0016 = M-Mode + CW Doppler + Color Doppler,
	0017 = 2D Imaging + M-Mode + CW Doppler + Color Doppler,
	0018 = PW Doppler + Color Doppler,
	0019 = 2D Imaging + PW Doppler + Color Doppler,
	001a = M-Mode + PW Doppler + Color Doppler,
	001b = 2D Imaging + M-Mode + PW Doppler + Color Doppler,
	001c = CW Doppler + PW Doppler + Color Doppler,
	001d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler,
	001e = M-Mode + CW Doppler + PW Doppler + Color Doppler,
	001f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler,
	0020 = Color M-Mode,
	0021 = 2D Imaging + Color M-Mode,
	0022 = M-Mode + Color M-Mode,
	0023 = 2D Imaging + M-Mode + Color M-Mode,
	0024 = CW Doppler + Color M-Mode,
	0025 = 2D Imaging + CW Doppler + Color M-Mode,
	0026 = M-Mode + CW Doppler + Color M-Mode,
	0027 = 2D Imaging + M-Mode + CW Doppler + Color M-Mode,
	0028 = PW Doppler + Color M-Mode,
	0029 = 2D Imaging + PW Doppler + Color M-Mode,
	002a = M-Mode + PW Doppler + Color M-Mode,
	002b = 2D Imaging + M-Mode + PW Doppler + Color M-Mode,
	002c = CW Doppler + PW Doppler + Color M-Mode,
	002d = 2D Imaging + CW Doppler + PW Doppler + Color M-Mode,
	002e = M-Mode + CW Doppler + PW Doppler + Color M-Mode,
	002f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color M-Mode,
	0030 = Color Doppler + Color M-Mode,
	0031 = 2D Imaging + Color Doppler + Color M-Mode,
	0032 = M-Mode + Color Doppler + Color M-Mode,
	0033 = 2D Imaging + M-Mode + Color Doppler + Color M-Mode,
	0034 = CW Doppler + Color Doppler + Color M-Mode,
	0035 = 2D Imaging + CW Doppler + Color Doppler + Color M-Mode,
	0036 = M-Mode + CW Doppler + Color Doppler + Color M-Mode,
	0037 = 2D Imaging + M-Mode + CW Doppler + Color Doppler + Color M-Mode,
	0038 = PW Doppler + Color Doppler + Color M-Mode,
	0039 = 2D Imaging + PW Doppler + Color Doppler + Color M-Mode,
	003a = M-Mode + PW Doppler + Color Doppler + Color M-Mode,
	003b = 2D Imaging + M-Mode + PW Doppler + Color Doppler + Color M-Mode,
	003c = CW Doppler + PW Doppler + Color Doppler + Color M-Mode,
	003d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler + Color M-Mode,
	003e = M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode,
	003f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode,
	0040 = 3D Rendering
	0041 = 2D Imaging + 3D Rendering,
	0042 = M-Mode + 3D Rendering,
	0043 = 2D Imaging + M-Mode + 3D Rendering,
	0044 = CW Doppler + 3D Rendering,
	0045 = 2D Imaging + CW Doppler + 3D Rendering,
	0046 = M-Mode + CW Doppler + 3D Rendering,
	0047 = 2D Imaging + M-Mode + CW Doppler + 3D Rendering,
	0048 = PW Doppler + 3D Rendering,
	0049 = 2D Imaging + PW Doppler + 3D Rendering,
	004a = M-Mode + PW Doppler + 3D Rendering,
	004b = 2D Imaging + M-Mode + PW Doppler + 3D Rendering,
	004c = CW Doppler + PW Doppler + 3D Rendering,
	004d = 2D Imaging + CW Doppler + PW Doppler + 3D Rendering,
	004e = M-Mode + CW Doppler + PW Doppler + 3D Rendering,
	004f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + 3D Rendering,
	0050 = Color Doppler + 3D Rendering,
	0051 = 2D Imaging + Color Doppler + 3D Rendering,
	0052 = M-Mode + Color Doppler + 3D Rendering,
	0053 = 2D Imaging + M-Mode + Color Doppler + 3D Rendering,
	0054 = CW Doppler + Color Doppler + 3D Rendering,
	0055 = 2D Imaging + CW Doppler + Color Doppler + 3D Rendering,
	0056 = M-Mode + CW Doppler + Color Doppler + 3D Rendering,
	0057 = 2D Imaging + M-Mode + CW Doppler + Color Doppler + 3D Rendering,
	0058 = PW Doppler + Color Doppler + 3D Rendering,
	0059 = 2D Imaging + PW Doppler + Color Doppler + 3D Rendering,
	005a = M-Mode + PW Doppler + Color Doppler + 3D Rendering,
	005b = 2D Imaging + M-Mode + PW Doppler + Color Doppler + 3D Rendering,
	005c = CW Doppler + PW Doppler + Color Doppler + 3D Rendering,
	005d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler + 3D Rendering,
	005e = M-Mode + CW Doppler + PW Doppler + Color Doppler + 3D Rendering,
	005f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler + 3D Rendering,
	0060 = Color M-Mode + 3D Rendering,
	0061 = 2D Imaging + Color M-Mode + 3D Rendering,
	0062 = M-Mode + Color M-Mode + 3D Rendering,
	0063 = 2D Imaging + M-Mode + Color M-Mode + 3D Rendering,
	0064 = CW Doppler + Color M-Mode + 3D Rendering,
	0065 = 2D Imaging + CW Doppler + Color M-Mode + 3D Rendering,
	0066 = M-Mode + CW Doppler + Color M-Mode + 3D Rendering,
	0067 = 2D Imaging + M-Mode + CW Doppler + Color M-Mode + 3D Rendering,
	0068 = PW Doppler + Color M-Mode + 3D Rendering,
	0069 = 2D Imaging + PW Doppler + Color M-Mode + 3D Rendering,
	006a = M-Mode + PW Doppler + Color M-Mode + 3D Rendering,
	006b = 2D Imaging + M-Mode + PW Doppler + Color M-Mode + 3D Rendering,
	006c = CW Doppler + PW Doppler + Color M-Mode + 3D Rendering,
	006d = 2D Imaging + CW Doppler + PW Doppler + Color M-Mode + 3D Rendering,
	006e = M-Mode + CW Doppler + PW Doppler + Color M-Mode + 3D Rendering,
	006f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color M-Mode + 3D Rendering,
	0070 = Color Doppler + Color M-Mode + 3D Rendering,
	0071 = 2D Imaging + Color Doppler + Color M-Mode + 3D Rendering,
	0072 = M-Mode + Color Doppler + Color M-Mode + 3D Rendering,
	0073 = 2D Imaging + M-Mode + Color Doppler + Color M-Mode + 3D Rendering,
	0074 = CW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	0075 = 2D Imaging + CW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	0076 = M-Mode + CW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	0077 = 2D Imaging + M-Mode + CW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	0078 = PW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	0079 = 2D Imaging + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	007a = M-Mode + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	007b = 2D Imaging + M-Mode + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	007c = CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	007d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	007e = M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering,
	007f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering
	0100 = Color Power Mode,
	0101 = 2D Imaging + Color Power Mode,
	0102 = M-Mode + Color Power Mode,
	0103 = 2D Imaging + M-Mode + Color Power Mode,
	0104 = CW Doppler + Color Power Mode,
	0105 = 2D Imaging + CW Doppler + Color Power Mode,
	0106 = M-Mode + CW Doppler + Color Power Mode,
	0107 = 2D Imaging + M-Mode + CW Doppler + Color Power Mode,
	0108 = PW Doppler + Color Power Mode,
	0109 = 2D Imaging + PW Doppler + Color Power Mode,
	010a = M-Mode + PW Doppler + Color Power Mode,
	010b = 2D Imaging + M-Mode + PW Doppler + Color Power Mode,
	010c = CW Doppler + PW Doppler + Color Power Mode,
	010d = 2D Imaging + CW Doppler + PW Doppler + Color Power Mode,
	010e = M-Mode + CW Doppler + PW Doppler + Color Power Mode,
	010f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Power Mode,
	0110 = Color Doppler + Color Power Mode,
	0111 = 2D Imaging + Color Doppler + Color Power Mode,
	0112 = M-Mode + Color Doppler + Color Power Mode,
	0113 = 2D Imaging + M-Mode + Color Doppler + Color Power Mode,
	0114 = CW Doppler + Color Doppler + Color Power Mode,
	0115 = 2D Imaging + CW Doppler + Color Doppler + Color Power Mode,
	0116 = M-Mode + CW Doppler + Color Doppler + Color Power Mode,
	0117 = 2D Imaging + M-Mode + CW Doppler + Color Doppler + Color Power Mode,
	0118 = PW Doppler + Color Doppler + Color Power Mode,
	0119 = 2D Imaging + PW Doppler + Color Doppler + Color Power Mode,
	011a = M-Mode + PW Doppler + Color Doppler + Color Power Mode,
	011b = 2D Imaging + M-Mode + PW Doppler + Color Doppler + Color Power Mode,
	011c = CW Doppler + PW Doppler + Color Doppler + Color Power Mode,
	011d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler + Color Power Mode,
	011e = M-Mode + CW Doppler + PW Doppler + Color Doppler + Color Power Mode,
	011f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler + Color Power Mode,
	0120 = Color M-Mode + Color Power Mode,
	0121 = 2D Imaging + Color M-Mode + Color Power Mode,
	0122 = M-Mode + Color M-Mode + Color Power Mode,
	0123 = 2D Imaging + M-Mode + Color M-Mode + Color Power Mode,
	0124 = CW Doppler + Color M-Mode + Color Power Mode,
	0125 = 2D Imaging + CW Doppler + Color M-Mode + Color Power Mode,
	0126 = M-Mode + CW Doppler + Color M-Mode + Color Power Mode,
	0127 = 2D Imaging + M-Mode + CW Doppler + Color M-Mode + Color Power Mode,
	0128 = PW Doppler + Color M-Mode + Color Power Mode,
	0129 = 2D Imaging + PW Doppler + Color M-Mode + Color Power Mode,
	012a = M-Mode + PW Doppler + Color M-Mode + Color Power Mode,
	012b = 2D Imaging + M-Mode + PW Doppler + Color M-Mode + Color Power Mode,
	012c = CW Doppler + PW Doppler + Color M-Mode + Color Power Mode,
	012d = 2D Imaging + CW Doppler + PW Doppler + Color M-Mode + Color Power Mode,
	012e = M-Mode + CW Doppler + PW Doppler + Color M-Mode + Color Power Mode,
	012f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color M-Mode + Color Power Mode,
	0130 = Color Doppler + Color M-Mode + Color Power Mode,
	0131 = 2D Imaging + Color Doppler + Color M-Mode + Color Power Mode,
	0132 = M-Mode + Color Doppler + Color M-Mode + Color Power Mode,
	0133 = 2D Imaging + M-Mode + Color Doppler + Color M-Mode + Color Power Mode,
	0134 = CW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	0135 = 2D Imaging + CW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	0136 = M-Mode + CW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	0137 = 2D Imaging + M-Mode + CW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	0138 = PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	0139 = 2D Imaging + PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	013a = M-Mode + PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	013b = 2D Imaging + M-Mode + PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	013c = CW Doppler + PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	013d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	013e = M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	013f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + Color Power Mode,
	0140 = 3D Rendering + Color Power Mode
	0141 = 2D Imaging + 3D Rendering + Color Power Mode,
	0142 = M-Mode + 3D Rendering + Color Power Mode,
	0143 = 2D Imaging + M-Mode + 3D Rendering + Color Power Mode,
	0144 = CW Doppler + 3D Rendering + Color Power Mode,
	0145 = 2D Imaging + CW Doppler + 3D Rendering + Color Power Mode,
	0146 = M-Mode + CW Doppler + 3D Rendering + Color Power Mode,
	0147 = 2D Imaging + M-Mode + CW Doppler + 3D Rendering + Color Power Mode,
	0148 = PW Doppler + 3D Rendering + Color Power Mode,
	0149 = 2D Imaging + PW Doppler + 3D Rendering + Color Power Mode,
	014a = M-Mode + PW Doppler + 3D Rendering + Color Power Mode,
	014b = 2D Imaging + M-Mode + PW Doppler + 3D Rendering + Color Power Mode,
	014c = CW Doppler + PW Doppler + 3D Rendering + Color Power Mode,
	014d = 2D Imaging + CW Doppler + PW Doppler + 3D Rendering + Color Power Mode,
	014e = M-Mode + CW Doppler + PW Doppler + 3D Rendering + Color Power Mode,
	014f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + 3D Rendering + Color Power Mode,
	0150 = Color Doppler + 3D Rendering + Color Power Mode,
	0151 = 2D Imaging + Color Doppler + 3D Rendering + Color Power Mode,
	0152 = M-Mode + Color Doppler + 3D Rendering + Color Power Mode,
	0153 = 2D Imaging + M-Mode + Color Doppler + 3D Rendering + Color Power Mode,
	0154 = CW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	0155 = 2D Imaging + CW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	0156 = M-Mode + CW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	0157 = 2D Imaging + M-Mode + CW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	0158 = PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	0159 = 2D Imaging + PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	015a = M-Mode + PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	015b = 2D Imaging + M-Mode + PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	015c = CW Doppler + PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	015d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	015e = M-Mode + CW Doppler + PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	015f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler + 3D Rendering + Color Power Mode,
	0160 = Color M-Mode + 3D Rendering + Color Power Mode,
	0161 = 2D Imaging + Color M-Mode + 3D Rendering + Color Power Mode,
	0162 = M-Mode + Color M-Mode + 3D Rendering + Color Power Mode,
	0163 = 2D Imaging + M-Mode + Color M-Mode + 3D Rendering + Color Power Mode,
	0164 = CW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0165 = 2D Imaging + CW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0166 = M-Mode + CW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0167 = 2D Imaging + M-Mode + CW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0168 = PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0169 = 2D Imaging + PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	016a = M-Mode + PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	016b = 2D Imaging + M-Mode + PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	016c = CW Doppler + PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	016d = 2D Imaging + CW Doppler + PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	016e = M-Mode + CW Doppler + PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	016f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0170 = Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0171 = 2D Imaging + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0172 = M-Mode + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0173 = 2D Imaging + M-Mode + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0174 = CW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0175 = 2D Imaging + CW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0176 = M-Mode + CW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0177 = 2D Imaging + M-Mode + CW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0178 = PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	0179 = 2D Imaging + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	017a = M-Mode + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	017b = 2D Imaging + M-Mode + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	017c = CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	017d = 2D Imaging + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	017e = M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode,
	017f = 2D Imaging + M-Mode + CW Doppler + PW Doppler + Color Doppler + Color M-Mode + 3D Rendering + Color Power Mode

}

StringValues="IVUSAcquisition" {
	MOTOR_PULLBACK,
	MANUAL_PULLBACK,
	SELECTIVE,
	GATED_PULLBACK
}

StringValues="FrameOfInterestTypeForUS" {
	HIGHMI,
	RWAVE,
	TRIGGER,
	ENDSYSTOLE
}

StringValues="USStageName" {
	PRE-EXERCISE,
	POST-EXERCISE,
	PEAK-EXERCISE,
	RECOVERY,
	BASELINE,
	LOW DOSE,
	PEAK DOSE
}



